import * as api from '../../api/office'

const unwrap = res => (res && res.data ? res.data : res)

export default {
  namespaced: true,
  state: { meetings: [], schedules: [], documents: [], approvals: [], templates: [], organization: null, notifications: [], unreadNotifications: 0, loading: false },
  mutations: {
    SET_LOADING(state, value) { state.loading = value },
    SET_MEETINGS(state, value) { state.meetings = value },
    SET_SCHEDULES(state, value) { state.schedules = value },
    SET_DOCUMENTS(state, value) { state.documents = value },
    SET_APPROVALS(state, value) { state.approvals = value },
    SET_ORGANIZATION(state, value) { state.organization = value },
    SET_NOTIFICATIONS(state, value) { state.notifications = value.items || []; state.unreadNotifications = value.unread_count || 0 },
    SET_TEMPLATES(state, value) { state.templates = value || [] },
  },
  actions: {
    async loadMeetings({ commit }, workspaceId) { const r = unwrap(await api.listMeetings({ workspace_id: workspaceId })); commit('SET_MEETINGS', r.items || r || []); return r },
    async loadSchedules({ commit }, workspaceId) { const r = unwrap(await api.listSchedules({ workspace_id: workspaceId })); commit('SET_SCHEDULES', r.items || r || []); return r },
    async loadDocuments({ commit }, workspaceId) { const r = unwrap(await api.listDocuments({ workspace_id: workspaceId })); commit('SET_DOCUMENTS', r.items || r || []); return r },
    async getDocument(_, id) { return unwrap(await api.getDocument(id)) },
    async loadApprovals({ commit }, workspaceId) { const r = unwrap(await api.listApprovals({ workspace_id: workspaceId })); commit('SET_APPROVALS', r.items || r || []); return r },
    async getApproval(_, id) { return unwrap(await api.getApproval(id)) },
    async loadOrganization({ commit }, workspaceId) { const r = unwrap(await api.getOrganization(workspaceId)); commit('SET_ORGANIZATION', r); return r },
    async bootstrapOrganization({ dispatch }, data) { const r = unwrap(await api.bootstrapOrganization(data)); await dispatch('loadOrganization', data.workspace_id); return r },
    async createGroup({ dispatch }, data) { const r = unwrap(await api.createGroup(data)); await dispatch('loadOrganization', data.workspace_id); return r },
    async addMember({ dispatch }, data) { await api.grantWorkspaceMember(data.workspace_id, data.user_id); const r = unwrap(await api.addMember(data)); await dispatch('loadOrganization', data.workspace_id); return r },
    async searchUsers(_, query) { return unwrap(await api.searchUsers(query)) },
    async loadNotifications({ commit }, workspaceId) { const r = unwrap(await api.listNotifications(workspaceId)); commit('SET_NOTIFICATIONS', r); return r },
    async readNotification({ dispatch }, { id, workspaceId }) { await api.readNotification(id); return dispatch('loadNotifications', workspaceId) },
    async loadTemplates({ commit }, workspaceId) { const r = unwrap(await api.listTemplates({ workspace_id: workspaceId })); commit('SET_TEMPLATES', r || []); return r },
    async createTemplate({ dispatch }, data) { const r = unwrap(await api.createTemplate(data)); await dispatch('loadTemplates', data.workspace_id); return r },
    async updateTemplate({ dispatch }, { id, data, workspaceId }) { const r = unwrap(await api.updateTemplate(id, data)); await dispatch('loadTemplates', workspaceId); return r },
    async deleteTemplate({ dispatch }, { id, workspaceId }) { const r = await api.deleteTemplate(id); await dispatch('loadTemplates', workspaceId); return r },
    async createMeeting({ dispatch }, data) { const r = await api.createMeeting(data); await dispatch('loadMeetings', data.workspace_id); return r },
    async updateMeeting({ dispatch }, { id, data, workspaceId }) { const r = await api.updateMeeting(id, data); await dispatch('loadMeetings', workspaceId); return r },
    async deleteMeeting({ dispatch }, { id, workspaceId }) { const r = await api.deleteMeeting(id); await Promise.all([dispatch('loadMeetings', workspaceId), dispatch('loadSchedules', workspaceId)]); return r },
    async getMeeting(_, id) { return unwrap(await api.getMeeting(id)) },
    async generateMeetingDraft(_, data) { return unwrap(await api.generateMeetingDraft(data)) },
    async generateDocumentDraft(_, data) { return unwrap(await api.generateDocumentDraft(data)) },
    async generateWeeklyDraft(_, data) { return unwrap(await api.generateWeeklyDraft(data)) },
    async createActionItem({ dispatch }, { meetingId, data, workspaceId }) { const r = await api.createActionItem(meetingId, data); await Promise.all([dispatch('loadMeetings', workspaceId), dispatch('loadSchedules', workspaceId)]); return r },
    async updateActionItem({ dispatch }, { id, data, workspaceId }) { const r = await api.updateActionItem(id, data); await Promise.all([dispatch('loadMeetings', workspaceId), dispatch('loadSchedules', workspaceId)]); return r },
    async createSchedule({ dispatch }, data) { const r = await api.createSchedule(data); await dispatch('loadSchedules', data.workspace_id); return r },
    async updateSchedule({ dispatch }, { id, data, workspaceId }) { const r = await api.updateSchedule(id, data); await dispatch('loadSchedules', workspaceId); return r },
    async createDocument({ dispatch }, data) { const r = await api.createDocument(data); await dispatch('loadDocuments', data.workspace_id); return r },
    async submitDocument({ dispatch }, { id, data, workspaceId }) { const r = await api.submitDocument(id, data); await Promise.all([dispatch('loadDocuments', workspaceId), dispatch('loadApprovals', workspaceId)]); return r },
    async publishDocument({ dispatch }, { id, workspaceId }) { const r = await api.publishDocument(id); await dispatch('loadDocuments', workspaceId); return r },
    async confirmDocumentReceipt({ dispatch }, { id, workspaceId }) { const r = await api.confirmDocumentReceipt(id); await dispatch('loadDocuments', workspaceId); return r },
    async approve({ dispatch }, { id, data, workspaceId }) { const r = await api.approveApproval(id, data); await Promise.all([dispatch('loadApprovals', workspaceId), dispatch('loadDocuments', workspaceId)]); return r },
    async reject({ dispatch }, { id, data, workspaceId }) { const r = await api.rejectApproval(id, data); await Promise.all([dispatch('loadApprovals', workspaceId), dispatch('loadDocuments', workspaceId)]); return r },
  },
}
