/**
 * RD 智能研发服务 — 演示数据（扩展版）
 *
 * 前端页面直接引用此文件作为初始展示数据。
 * 后端 API 就绪后，只需将数据源切换到 API 即可无缝衔接。
 */

// ── 工具函数 ──────────────────────────────────────────────────
const daysAgo = (n) => {
  const d = new Date()
  d.setDate(d.getDate() - n)
  return d.toISOString()
}

// ── 开发者列表 ─────────────────────────────────────────────────
export const developers = [
  { id: 'dev-1', name: '张伟', avatar: '', role: '前端开发' },
  { id: 'dev-2', name: '李娜', avatar: '', role: '后端开发' },
  { id: 'dev-3', name: '王磊', avatar: '', role: '全栈开发' },
  { id: 'dev-4', name: '陈静', avatar: '', role: '前端开发' },
  { id: 'dev-5', name: '赵敏', avatar: '', role: '前端开发' },
  { id: 'dev-6', name: '刘洋', avatar: '', role: '测试工程师' },
]

// ── 演示项目 ──────────────────────────────────────────────────
export const demoProjects = [
  {
    id: 'proj-1',
    name: '用户反馈系统',
    description: '收集和管理用户反馈的全栈应用，支持反馈提交、分类、处理和数据分析',
    cover_url: '',
    tech_stack: { frontend: 'Vue 3 + Element Plus', backend: 'Flask', database: 'MySQL', deployment: 'Docker' },
    coding_standards: [
      'ESLint (airbnb-base) 代码规范',
      'Prettier 统一格式化',
      'Git Commit 遵循 Conventional Commits',
      '组件必须包含 Props 类型定义',
      'API 接口必须有 Swagger 文档',
    ],
    visibility: 'private',
    status: 'active',
    file_count: 23,
    members: [
      { user_id: 'dev-1', user_name: '张伟', role: 'owner' },
      { user_id: 'dev-2', user_name: '李娜', role: 'admin' },
      { user_id: 'dev-4', user_name: '陈静', role: 'developer' },
      { user_id: 'dev-6', user_name: '刘洋', role: 'viewer' },
    ],
    updated_at: daysAgo(0.1),
    created_at: daysAgo(30),
  },
  {
    id: 'proj-2',
    name: 'API 网关服务',
    description: '统一的 API 网关，负责流量路由、认证鉴权、限流熔断和日志采集',
    cover_url: '',
    tech_stack: { frontend: '无', backend: 'Go + Gin', database: 'PostgreSQL', deployment: 'K8s' },
    coding_standards: [
      'gofmt 代码格式化',
      'golangci-lint 静态检查',
      'Git Commit 遵循 Conventional Commits',
      '所有公开函数必须有 GoDoc 注释',
      '单元测试覆盖率 > 80%',
    ],
    visibility: 'internal',
    status: 'active',
    file_count: 15,
    members: [
      { user_id: 'dev-3', user_name: '王磊', role: 'owner' },
      { user_id: 'dev-2', user_name: '李娜', role: 'admin' },
      { user_id: 'dev-5', user_name: '赵敏', role: 'developer' },
      { user_id: 'dev-6', user_name: '刘洋', role: 'tester' },
    ],
    updated_at: daysAgo(2),
    created_at: daysAgo(60),
  },
  {
    id: 'proj-3',
    name: '内部工具集',
    description: '研发效率工具集合，包括代码生成器、数据迁移脚本、性能分析面板',
    cover_url: '',
    tech_stack: { frontend: 'React + Ant Design', backend: 'Python FastAPI', database: 'SQLite', deployment: 'Docker Compose' },
    coding_standards: [
      'Prettier + ESLint 代码规范',
      'Black + isort Python 格式化',
      'Git Commit 遵循 Conventional Commits',
      'React 组件使用 TypeScript',
    ],
    visibility: 'internal',
    status: 'archived',
    file_count: 8,
    members: [
      { user_id: 'dev-1', user_name: '张伟', role: 'owner' },
      { user_id: 'dev-3', user_name: '王磊', role: 'admin' },
      { user_id: 'dev-4', user_name: '陈静', role: 'developer' },
      { user_id: 'dev-6', user_name: '刘洋', role: 'viewer' },
    ],
    updated_at: daysAgo(45),
    created_at: daysAgo(90),
  },
]

// ── 演示迭代 ──────────────────────────────────────────────────
export const demoIterations = [
  {
    id: 'iter-1',
    project_id: 'proj-1',
    name: 'Sprint 1 — 反馈提交与展示',
    goal: '**核心目标：打通用户反馈闭环**\n\n- **反馈表单页** — 支持类型选择、富文本输入、图片拖拽上传、联系方式校验\n- **反馈数据 API** — RESTful 接口，支持分页查询、条件筛选、状态流转\n- **管理员列表页** — 表格展示 + 行内编辑 + 批量操作 + 导出 CSV\n\n`预计工时 80h` | `优先级 P0`',
    start_date: '2026-07-13',
    end_date: '2026-07-27',
    status: 'active',
    sort_order: 1,
    progress_manual: 65,
    progress_auto: 58,
    created_at: daysAgo(15),
  },
  {
    id: 'iter-2',
    project_id: 'proj-1',
    name: 'Sprint 2 — 反馈处理工作流',
    goal: '**目标：构建智能反馈处理引擎**\n\n- **智能分类** — 基于关键词 + NLP 模型自动归类 Bug / 建议 / 咨询\n- **自动指派** — 按模块负责人 + 负载均衡策略自动分配处理人\n- **状态流转** — 待处理 → 处理中 → 已解决 → 已关闭，支持驳回和转派\n- **邮件通知** — 状态变更、新评论、即将超时时自动发送提醒邮件\n\n`预计工时 60h` | `优先级 P1` | `依赖 Sprint 1`',
    start_date: '2026-07-28',
    end_date: '2026-08-10',
    status: 'planning',
    sort_order: 2,
    progress_manual: 0,
    progress_auto: 0,
    created_at: daysAgo(1),
  },
  {
    id: 'iter-3',
    project_id: 'proj-1',
    name: 'Sprint 0 — 项目初始化',
    goal: '**目标：从零搭建工程化基础设施**\n\n- **项目骨架** — Monorepo 结构 + ESLint/Prettier 统一规范 + Git Hooks 提交检查\n- **CI/CD 流水线** — GitHub Actions 自动化: `lint → test → build → deploy`\n- **开发环境** — Docker Compose 一键启动，含 MySQL/Redis/Nginx\n- **技术栈定型** — 前端 Vue2 + Element UI | 后端 Flask | 数据库 MySQL\n\n`实际工时 72h` | `状态: 已完成`',
    start_date: '2026-06-28',
    end_date: '2026-07-11',
    status: 'completed',
    sort_order: 0,
    progress_manual: 100,
    progress_auto: 100,
    created_at: daysAgo(30),
  },
  {
    id: 'iter-4',
    project_id: 'proj-2',
    name: 'Sprint 1 — 核心网关功能',
    goal: '实现路由转发、认证鉴权中间件、基础限流功能、健康检查端点',
    start_date: '2026-07-15',
    end_date: '2026-08-05',
    status: 'active',
    sort_order: 1,
    progress_manual: 40,
    progress_auto: 35,
    created_at: daysAgo(14),
  },
]

// ── 演示需求 ──────────────────────────────────────────────────
export const demoRequirements = [
  {
    id: 'req-1',
    project_id: 'proj-1',
    iteration_id: 'iter-1',
    iteration_name: 'Sprint 1',
    title: '反馈提交表单页面',
    description: '用户可以在前端页面提交反馈，包含反馈类型选择、文本输入、图片上传、联系方式填写等字段。表单需做前端校验。',
    acceptance_criteria: [
      '用户可选择反馈类型（Bug/建议/咨询/投诉）并成功提交',
      '表单前端校验提示准确，必填项未填时不可提交',
      '图片上传支持 jpg/png/gif 格式，单张不超过 5MB',
      '联系方式邮箱格式校验正确',
      '提交成功后显示成功提示并清空表单',
    ],
    type: 'feature',
    priority: 'p1',
    status: 'in_review',
    assignee_id: 'dev-1',
    assignee_name: '张伟',
    assignees: [
      { user_id: 'dev-1', role: 'primary' },
      { user_id: 'dev-4', role: 'reviewer' },
    ],
    story_points: 5,
    labels: ['前端', '表单', '用户体验'],
    start_date: '2026-07-13',
    due_date: '2026-07-22',
    created_by: 'dev-1',
    created_at: daysAgo(14),
    updated_at: daysAgo(1),
  },
  {
    id: 'req-1-1',
    project_id: 'proj-1',
    iteration_id: 'iter-1',
    iteration_name: 'Sprint 1',
    parent_id: 'req-1',
    title: '反馈类型选择器组件',
    description: '抽取反馈类型选择为独立可复用组件，支持图标+文字展示，支持搜索过滤。',
    acceptance_criteria: [
      '组件支持 4 种反馈类型的展示和选择',
      '可选择显示为下拉框或单选按钮组两种模式',
      '键盘导航支持（上下箭头选择，回车确认）',
    ],
    type: 'feature',
    priority: 'p1',
    status: 'completed',
    assignee_id: 'dev-1',
    assignee_name: '张伟',
    assignees: [
      { user_id: 'dev-1', role: 'primary' },
    ],
    story_points: 2,
    labels: ['前端', '组件'],
    start_date: '2026-07-13',
    due_date: '2026-07-16',
    created_by: 'dev-1',
    created_at: daysAgo(14),
    updated_at: daysAgo(7),
  },
  {
    id: 'req-1-2',
    project_id: 'proj-1',
    iteration_id: 'iter-1',
    iteration_name: 'Sprint 1',
    parent_id: 'req-1',
    title: '图片上传与预览组件',
    description: '实现图片多图上传、拖拽排序、缩略图预览、删除确认等功能。上传前自动压缩。',
    acceptance_criteria: [
      '支持一次性选择最多 5 张图片',
      '上传前自动压缩至最大宽度 1920px',
      '拖拽调整图片顺序',
      '点击缩略图可全屏预览',
      '单张超过 5MB 时给出提示',
    ],
    type: 'feature',
    priority: 'p2',
    status: 'in_progress',
    assignee_id: 'dev-1',
    assignee_name: '张伟',
    assignees: [
      { user_id: 'dev-1', role: 'primary' },
      { user_id: 'dev-4', role: 'reviewer' },
    ],
    story_points: 3,
    labels: ['前端', '组件', '图片'],
    start_date: '2026-07-17',
    due_date: '2026-07-21',
    created_by: 'dev-1',
    created_at: daysAgo(10),
    updated_at: daysAgo(2),
  },
  {
    id: 'req-2',
    project_id: 'proj-1',
    iteration_id: 'iter-1',
    iteration_name: 'Sprint 1',
    title: '反馈数据 API',
    description: '设计和实现反馈数据的 CRUD RESTful API，支持分页查询、按类型/状态筛选、排序功能。需要添加 JWT 鉴权。',
    acceptance_criteria: [
      'POST /api/feedback 创建反馈返回 201 和完整数据',
      'GET /api/feedback?page=1&per_page=20&type=bug 正确分页筛选',
      'GET /api/feedback/:id 返回单条完整数据',
      'PATCH /api/feedback/:id 更新状态并验证状态流转合法性',
      'DELETE /api/feedback/:id 仅管理员可执行',
      '未携带有效 JWT 的请求返回 401',
      'API 响应时间 p95 < 200ms',
    ],
    type: 'feature',
    priority: 'p1',
    status: 'in_progress',
    assignee_id: 'dev-2',
    assignee_name: '李娜',
    assignees: [
      { user_id: 'dev-2', role: 'primary' },
      { user_id: 'dev-3', role: 'reviewer' },
    ],
    story_points: 3,
    labels: ['后端', 'API', '数据库'],
    start_date: '2026-07-13',
    due_date: '2026-07-20',
    created_by: 'dev-2',
    created_at: daysAgo(14),
    updated_at: daysAgo(3),
  },
  {
    id: 'req-3',
    project_id: 'proj-1',
    iteration_id: 'iter-1',
    iteration_name: 'Sprint 1',
    title: '管理员反馈列表页',
    description: '管理员可以查看所有用户提交的反馈，支持表格展示、高级筛选（类型/状态/日期范围）、批量操作（标记已处理/删除）。',
    acceptance_criteria: [
      '表格展示所有反馈记录，支持按创建时间倒序排列',
      '高级筛选面板支持类型、状态、日期范围的组合筛选',
      '支持批量勾选并执行"标记已处理"或"批量删除"',
      '操作需要有二次确认弹窗',
      '分页切换时筛选条件不丢失',
    ],
    type: 'feature',
    priority: 'p2',
    status: 'todo',
    assignee_id: 'dev-1',
    assignee_name: '张伟',
    assignees: [
      { user_id: 'dev-1', role: 'primary' },
      { user_id: 'dev-6', role: 'tester' },
    ],
    story_points: 3,
    labels: ['前端', '管理后台', '表格'],
    start_date: '2026-07-20',
    due_date: '2026-07-27',
    created_by: 'dev-1',
    created_at: daysAgo(12),
    updated_at: daysAgo(5),
  },
  {
    id: 'req-4',
    project_id: 'proj-1',
    iteration_id: 'iter-2',
    iteration_name: 'Sprint 2',
    title: '反馈自动分类引擎',
    description: '基于 NLP 模型自动识别反馈类型（Bug/建议/咨询/投诉），减少人工分类工作量。准确率目标 > 85%。',
    acceptance_criteria: [
      '文本分类准确率在测试集上 > 85%',
      '单条反馈分类耗时 < 100ms',
      '支持人工修正分类结果并反馈给模型',
      '分类结果记录置信度分数',
      '低置信度（< 0.6）的反馈标记为待人工审核',
    ],
    type: 'enhancement',
    priority: 'p2',
    status: 'backlog',
    assignee_id: 'dev-3',
    assignee_name: '王磊',
    assignees: [
      { user_id: 'dev-3', role: 'primary' },
    ],
    story_points: 8,
    labels: ['后端', 'AI', 'NLP'],
    start_date: '2026-07-28',
    due_date: '2026-08-10',
    created_by: 'dev-3',
    created_at: daysAgo(1),
  },
  {
    id: 'req-5',
    project_id: 'proj-1',
    iteration_id: 'iter-2',
    iteration_name: 'Sprint 2',
    title: '邮件通知服务',
    description: '当反馈状态变更时（新建/处理中/已解决），自动发送邮件通知给提交者和相关处理人。支持邮件模板自定义。',
    acceptance_criteria: [
      '反馈状态变更时自动触发邮件发送',
      '邮件包含反馈标题、状态变更、处理人信息',
      '支持 HTML 邮件模板，管理员可在线编辑模板',
      '发送失败时自动重试 3 次，间隔 5 分钟',
      '记录所有邮件发送日志供排查',
    ],
    type: 'feature',
    priority: 'p2',
    status: 'backlog',
    assignee_id: 'dev-2',
    assignee_name: '李娜',
    assignees: [
      { user_id: 'dev-2', role: 'primary' },
    ],
    story_points: 3,
    labels: ['后端', '通知', '邮件'],
    start_date: '2026-08-01',
    due_date: '2026-08-07',
    created_by: 'dev-2',
    created_at: daysAgo(1),
  },
  {
    id: 'req-6',
    project_id: 'proj-1',
    iteration_id: null,
    iteration_name: null,
    title: '反馈数据分析仪表盘',
    description: '可视化展示反馈数据：时间趋势图、类型分布饼图、处理效率统计、热门反馈词云等。',
    acceptance_criteria: [
      '时间趋势图展示近 30 天反馈数量变化',
      '类型分布饼图支持点击钻取',
      '处理效率统计展示平均处理时长',
      '仪表盘数据每日凌晨自动刷新',
      '支持导出统计报表为 PDF',
    ],
    type: 'enhancement',
    priority: 'p3',
    status: 'backlog',
    assignee_id: null,
    assignee_name: null,
    assignees: [],
    story_points: 5,
    labels: ['前端', '数据分析', '可视化'],
    created_by: 'dev-1',
    created_at: daysAgo(7),
    updated_at: daysAgo(7),
  },
  {
    id: 'req-7',
    project_id: 'proj-2',
    iteration_id: 'iter-4',
    iteration_name: 'Sprint 1',
    title: '统一认证鉴权中间件',
    description: '实现 JWT Token 验证中间件，支持 Token 解析、过期检查、权限校验。需集成多种认证方式（Bearer Token、API Key、OAuth2）。',
    acceptance_criteria: [
      'Bearer Token 解析正确，支持 RS256/HS256 两种算法',
      'Token 过期自动返回 401 并附带友好提示',
      'API Key 验证延迟 < 5ms',
      '支持白名单路径配置（无需认证的端点）',
      'OAuth2 回调流程完整可用',
      '认证失败记录审计日志',
    ],
    type: 'feature',
    priority: 'p0',
    status: 'in_progress',
    assignee_id: 'dev-3',
    assignee_name: '王磊',
    assignees: [
      { user_id: 'dev-3', role: 'primary' },
      { user_id: 'dev-2', role: 'reviewer' },
      { user_id: 'dev-6', role: 'tester' },
    ],
    story_points: 8,
    labels: ['后端', '安全', '认证'],
    start_date: '2026-07-15',
    due_date: '2026-07-30',
    created_by: 'dev-3',
    created_at: daysAgo(14),
    updated_at: daysAgo(2),
  },
  {
    id: 'req-8',
    project_id: 'proj-2',
    iteration_id: 'iter-4',
    iteration_name: 'Sprint 1',
    title: '限流与熔断功能',
    description: '实现基于令牌桶算法的限流机制和熔断器模式。支持按 API 路径、用户、IP 维度配置限流策略，以及下游服务熔断自动恢复。',
    acceptance_criteria: [
      '令牌桶算法限流精确，误差 < 5%',
      '支持每秒/每分钟/每小时三种限流粒度',
      '限流配置支持热更新，无需重启服务',
      '熔断器在半开状态正确探测下游服务恢复',
      '熔断触发和恢复时发送告警通知',
      '限流和熔断指标接入 Prometheus',
    ],
    type: 'feature',
    priority: 'p1',
    status: 'todo',
    assignee_id: 'dev-5',
    assignee_name: '赵敏',
    assignees: [
      { user_id: 'dev-5', role: 'primary' },
      { user_id: 'dev-3', role: 'reviewer' },
    ],
    story_points: 5,
    labels: ['后端', '限流', '熔断'],
    start_date: '2026-07-22',
    due_date: '2026-08-05',
    created_by: 'dev-3',
    created_at: daysAgo(10),
    updated_at: daysAgo(5),
  },
]

// ── 演示 Bug ──────────────────────────────────────────────────
export const demoBugs = [
  {
    id: 'bug-1',
    project_id: 'proj-1',
    iteration_id: 'iter-1',
    iteration_name: 'Sprint 1',
    requirement_id: 'req-1',
    title: '反馈提交按钮在 Safari 下点击无响应',
    description: '在 Safari 17.0 浏览器中，填写完反馈表单后点击"提交"按钮没有任何反应，控制台无报错。Chrome/Firefox 正常。',
    expected_behavior: '点击提交按钮后，表单数据发送到后端，显示提交成功提示',
    actual_behavior: '点击按钮后页面无任何响应，网络请求未发出',
    severity: 'critical',
    priority: 'p0',
    status: 'in_progress',
    assignee_id: 'dev-1',
    assignee_name: '张伟',
    assignees: [
      { user_id: 'dev-1', role: 'fixer' },
      { user_id: 'dev-6', role: 'tester' },
    ],
    environment: 'macOS 14.0, Safari 17.0',
    browser_info: 'Safari 17.0',
    os_info: 'macOS 14.0 Sonoma',
    attachments: [
      'https://example.com/screenshots/bug-001-safari-blank.png',
      'https://example.com/logs/bug-001-console.log',
    ],
    labels: ['前端', '浏览器兼容', 'Safari'],
    created_by: 'dev-6',
    created_at: daysAgo(5),
    updated_at: daysAgo(2),
  },
  {
    id: 'bug-2',
    project_id: 'proj-1',
    iteration_id: 'iter-1',
    iteration_name: 'Sprint 1',
    requirement_id: 'req-2',
    title: '反馈内容超过 1000 字时 API 返回 500',
    description: '当用户提交的反馈内容超过 1000 个字符时，POST /api/feedback 返回 500 Internal Server Error。数据库字段可能长度不足。',
    expected_behavior: '支持最多 5000 字符的反馈内容',
    actual_behavior: '超过 1000 字符时返回 500 错误',
    severity: 'major',
    priority: 'p1',
    status: 'fixed',
    assignee_id: 'dev-2',
    assignee_name: '李娜',
    assignees: [
      { user_id: 'dev-2', role: 'fixer' },
      { user_id: 'dev-6', role: 'tester' },
    ],
    environment: '全平台',
    browser_info: 'Chrome 120',
    os_info: 'Windows 11',
    attachments: [
      'https://example.com/screenshots/bug-002-500-error.png',
      'https://example.com/logs/bug-002-server-error.log',
    ],
    labels: ['后端', 'API', '数据库'],
    created_by: 'dev-6',
    created_at: daysAgo(8),
    updated_at: daysAgo(3),
  },
  {
    id: 'bug-3',
    project_id: 'proj-1',
    iteration_id: 'iter-1',
    iteration_name: 'Sprint 1',
    requirement_id: 'req-3',
    title: '管理员列表页分页切换后筛选条件丢失',
    description: '在管理员反馈列表页，先选择"类型=Bug"筛选，然后点击第2页，筛选条件被重置为全部。',
    expected_behavior: '切换分页时保持当前筛选条件',
    actual_behavior: '分页后筛选条件丢失，显示全部数据',
    severity: 'minor',
    priority: 'p2',
    status: 'confirmed',
    assignee_id: 'dev-4',
    assignee_name: '陈静',
    assignees: [
      { user_id: 'dev-4', role: 'fixer' },
      { user_id: 'dev-1', role: 'reviewer' },
    ],
    environment: 'Chrome 120, Windows 11',
    browser_info: 'Chrome 120',
    os_info: 'Windows 11',
    attachments: [
      'https://example.com/screenshots/bug-003-filter-reset.mp4',
    ],
    labels: ['前端', '分页', '状态管理'],
    created_by: 'dev-6',
    created_at: daysAgo(3),
  },
  {
    id: 'bug-4',
    project_id: 'proj-1',
    iteration_id: null,
    iteration_name: null,
    requirement_id: 'req-1',
    title: '首页加载速度慢，首屏时间超过 3 秒',
    description: 'Chrome DevTools Lighthouse 报告首页 Performance 评分仅 45 分。首屏内容渲染时间 3.2s。',
    expected_behavior: '首屏时间 < 1.5s，Performance 评分 > 80',
    actual_behavior: '首屏时间 3.2s，Performance 45 分',
    severity: 'major',
    priority: 'p2',
    status: 'open',
    assignee_id: null,
    assignee_name: null,
    assignees: [],
    environment: 'Chrome 120, Fast 3G throttling',
    browser_info: 'Chrome 120',
    os_info: 'Windows 11',
    attachments: [
      'https://example.com/screenshots/bug-004-lighthouse-report.pdf',
    ],
    labels: ['前端', '性能优化'],
    created_by: 'dev-3',
    created_at: daysAgo(2),
  },
  {
    id: 'bug-5',
    project_id: 'proj-2',
    iteration_id: 'iter-4',
    iteration_name: 'Sprint 1',
    requirement_id: 'req-7',
    title: 'JWT Token 过期后前端未自动刷新导致请求失败',
    description: '用户在页面停留超过 Token 有效期（30分钟）后，所有 API 请求返回 401，但前端未自动调用 refresh token 接口刷新。',
    expected_behavior: 'Token 过期前 5 分钟自动刷新，或请求返回 401 后静默刷新 Token 并重试原请求',
    actual_behavior: 'Token 过期后所有请求直接失败，用户必须刷新页面重新登录',
    severity: 'major',
    priority: 'p1',
    status: 'confirmed',
    assignee_id: 'dev-5',
    assignee_name: '赵敏',
    assignees: [
      { user_id: 'dev-5', role: 'fixer' },
      { user_id: 'dev-3', role: 'reviewer' },
      { user_id: 'dev-6', role: 'tester' },
    ],
    environment: '全平台',
    browser_info: 'Chrome 120',
    os_info: 'macOS 14.0',
    attachments: [
      'https://example.com/screenshots/bug-005-token-expired.png',
      'https://example.com/logs/bug-005-network-har.har',
    ],
    labels: ['前端', '认证', 'Token'],
    created_by: 'dev-6',
    created_at: daysAgo(4),
    updated_at: daysAgo(1),
  },
  {
    id: 'bug-6',
    project_id: 'proj-2',
    iteration_id: 'iter-4',
    iteration_name: 'Sprint 1',
    requirement_id: 'req-8',
    title: '限流配置通过 API 更新后不生效，需重启服务',
    description: '通过管理 API PATCH /admin/rate-limit 更新限流配置后，内存中的限流器参数未实时更新，直到服务重启才加载新配置。',
    expected_behavior: '配置更新后，限流器应在 5 秒内加载新参数并生效',
    actual_behavior: '配置更新 API 返回 200，但限流行为仍使用旧参数',
    severity: 'major',
    priority: 'p1',
    status: 'open',
    assignee_id: 'dev-5',
    assignee_name: '赵敏',
    assignees: [
      { user_id: 'dev-5', role: 'fixer' },
    ],
    environment: '全平台',
    browser_info: 'N/A',
    os_info: 'Linux (K8s pod)',
    attachments: [
      'https://example.com/logs/bug-006-rate-limit-config.log',
    ],
    labels: ['后端', '限流', '配置'],
    created_by: 'dev-3',
    created_at: daysAgo(2),
  },
]

// ── 演示评论 ──────────────────────────────────────────────────
export const demoComments = [
  // ── req-1 的评论 ──
  {
    id: 'comment-1',
    target_type: 'requirement',
    target_id: 'req-1',
    parent_id: null,
    content: '表单校验规则已经写好，大家看一下 `FeedbackForm.vue` 里的 `rules` 对象，有什么遗漏的校验项吗？',
    author_id: 'dev-1',
    author_name: '张伟',
    is_pinned: false,
    created_at: daysAgo(10),
  },
  {
    id: 'comment-2',
    target_type: 'requirement',
    target_id: 'req-1',
    parent_id: 'comment-1',
    content: '我看了下，建议加上**联系方式去重校验**，同一个邮箱重复提交时需要提示用户"该邮箱已有反馈记录"。',
    author_id: 'dev-4',
    author_name: '陈静',
    is_pinned: false,
    created_at: daysAgo(9),
  },
  {
    id: 'comment-3',
    target_type: 'requirement',
    target_id: 'req-1',
    parent_id: 'comment-1',
    content: '还有图片上传的大小也需要前端校验一下，后端已经做了 5MB 限制，前端也加一下避免用户传了才发现。',
    author_id: 'dev-2',
    author_name: '李娜',
    is_pinned: false,
    created_at: daysAgo(9),
  },
  {
    id: 'comment-4',
    target_type: 'requirement',
    target_id: 'req-1',
    parent_id: null,
    content: '补充一下，表单的 `autocomplete` 属性要设置对，方便用户快速填写。参考 MDN 文档：\n\n```html\n<input name="email" autocomplete="email" />\n```',
    author_id: 'dev-1',
    author_name: '张伟',
    is_pinned: false,
    created_at: daysAgo(7),
  },
  {
    id: 'comment-5',
    target_type: 'requirement',
    target_id: 'req-1',
    parent_id: null,
    content: '**状态变更**：需求状态由「开发中」变更为「待审查」',
    author_id: 'system',
    author_name: '系统',
    is_pinned: false,
    created_at: daysAgo(2),
  },
  // ── req-2 的评论 ──
  {
    id: 'comment-6',
    target_type: 'requirement',
    target_id: 'req-2',
    parent_id: null,
    content: 'API 接口设计文档已更新到 Swagger，地址：`/api/docs`。\n\n主要变更：\n1. 返回格式统一为 `{ code, data, message }`\n2. 分页参数名改为 `page` / `page_size`\n3. 新增 `sort_by` 和 `sort_order` 查询参数',
    author_id: 'dev-2',
    author_name: '李娜',
    is_pinned: true,
    created_at: daysAgo(12),
  },
  {
    id: 'comment-7',
    target_type: 'requirement',
    target_id: 'req-2',
    parent_id: 'comment-6',
    content: 'Swagger 文档看起来很清晰。有一个小建议：是否考虑在响应头 `X-Total-Count` 中返回总数？这样前端做分页时不用额外请求。',
    author_id: 'dev-1',
    author_name: '张伟',
    is_pinned: false,
    created_at: daysAgo(11),
  },
  {
    id: 'comment-8',
    target_type: 'requirement',
    target_id: 'req-2',
    parent_id: 'comment-7',
    content: '好主意，已添加 `X-Total-Count` 和 `X-Total-Pages` 响应头，代码已提交到 `feature/REQ-002-feedback-api` 分支。',
    author_id: 'dev-2',
    author_name: '李娜',
    is_pinned: false,
    created_at: daysAgo(10),
  },
  {
    id: 'comment-9',
    target_type: 'requirement',
    target_id: 'req-2',
    parent_id: null,
    content: '**状态变更**：需求状态由「待处理」变更为「进行中」',
    author_id: 'system',
    author_name: '系统',
    is_pinned: false,
    created_at: daysAgo(13),
  },
  // ── req-7 的评论 ──
  {
    id: 'comment-10',
    target_type: 'requirement',
    target_id: 'req-7',
    parent_id: null,
    content: '关于 OAuth2 的集成方案，我建议参考 [RFC 6749](https://datatracker.ietf.org/doc/html/rfc6749) 标准实现。\n\n目前计划支持的 grant type：\n- `authorization_code`\n- `client_credentials`\n- `refresh_token`\n\nPKCE 扩展也需要支持（用于 SPA 场景）。',
    author_id: 'dev-3',
    author_name: '王磊',
    is_pinned: true,
    created_at: daysAgo(12),
  },
  {
    id: 'comment-11',
    target_type: 'requirement',
    target_id: 'req-7',
    parent_id: 'comment-10',
    content: 'PKCE 是必须的，现在安全审核对 SPA 的 OAuth2 实现要求越来越严了。另外问一下，JWT 的 key rotation 策略有考虑吗？',
    author_id: 'dev-2',
    author_name: '李娜',
    is_pinned: false,
    created_at: daysAgo(11),
  },
  {
    id: 'comment-12',
    target_type: 'requirement',
    target_id: 'req-7',
    parent_id: 'comment-11',
    content: 'Key rotation 放在第二个迭代做吧，Sprint 1 先用固定的 RSA 密钥对。我已经建了 backlog 需求来跟踪。',
    author_id: 'dev-3',
    author_name: '王磊',
    is_pinned: false,
    created_at: daysAgo(10),
  },
  // ── bug-1 的评论 ──
  {
    id: 'comment-13',
    target_type: 'bug',
    target_id: 'bug-1',
    parent_id: null,
    content: '定位到原因了：Safari 对 `<button type="submit">` 的 `@click` 事件处理方式和 Chrome 不同。\n\n解决方案：改用 `<form @submit.prevent>` 事件，这样所有浏览器行为一致。\n\n修复分支：`fix/BUG-001-safari-submit`',
    author_id: 'dev-1',
    author_name: '张伟',
    is_pinned: false,
    created_at: daysAgo(3),
  },
  {
    id: 'comment-14',
    target_type: 'bug',
    target_id: 'bug-1',
    parent_id: 'comment-13',
    content: '修复验证通过。我在 Safari 17.0 / 17.1 / 17.2 三个版本都测了，提交按钮可以正常响应。可以合并到 main 了。',
    author_id: 'dev-6',
    author_name: '刘洋',
    is_pinned: false,
    created_at: daysAgo(2),
  },
  {
    id: 'comment-15',
    target_type: 'bug',
    target_id: 'bug-1',
    parent_id: null,
    content: '**状态变更**：Bug 状态由「待确认」变更为「修复中」',
    author_id: 'system',
    author_name: '系统',
    is_pinned: false,
    created_at: daysAgo(4),
  },
  // ── bug-2 的评论 ──
  {
    id: 'comment-16',
    target_type: 'bug',
    target_id: 'bug-2',
    parent_id: null,
    content: '原因找到了：MySQL 的 `content` 字段定义为 `VARCHAR(1000)`，超过 1000 字符时插入失败抛异常。\n\n已执行 migration 将字段改为 `TEXT` 类型，并在 API 层加了 `maxlength=5000` 校验。',
    author_id: 'dev-2',
    author_name: '李娜',
    is_pinned: false,
    created_at: daysAgo(5),
  },
  {
    id: 'comment-17',
    target_type: 'bug',
    target_id: 'bug-2',
    parent_id: null,
    content: '**状态变更**：Bug 状态由「修复中」变更为「已修复」',
    author_id: 'system',
    author_name: '系统',
    is_pinned: false,
    created_at: daysAgo(3),
  },
  {
    id: 'comment-18',
    target_type: 'bug',
    target_id: 'bug-2',
    parent_id: null,
    content: '回归测试通过。提交超过 1000 字的内容现在可以正常保存和显示了。关闭此 Bug。',
    author_id: 'dev-6',
    author_name: '刘洋',
    is_pinned: false,
    created_at: daysAgo(2),
  },
]

// ── 演示分支 ──────────────────────────────────────────────────
export const demoBranches = [
  { id: 'br-1', project_id: 'proj-1', repo_id: 'repo-1', branch_name: 'feature/REQ-001-feedback-form', source_type: 'requirement', source_id: 'req-1', base_branch: 'main', status: 'active', created_by: 'dev-1', created_at: daysAgo(14) },
  { id: 'br-2', project_id: 'proj-1', repo_id: 'repo-1', branch_name: 'feature/REQ-002-feedback-api', source_type: 'requirement', source_id: 'req-2', base_branch: 'main', status: 'active', created_by: 'dev-2', created_at: daysAgo(13) },
  { id: 'br-3', project_id: 'proj-1', repo_id: 'repo-1', branch_name: 'fix/BUG-001-safari-submit', source_type: 'bug', source_id: 'bug-1', base_branch: 'main', status: 'active', created_by: 'dev-1', created_at: daysAgo(4) },
  { id: 'br-4', project_id: 'proj-1', repo_id: 'repo-1', branch_name: 'fix/BUG-002-content-length', source_type: 'bug', source_id: 'bug-2', base_branch: 'main', status: 'merged', created_by: 'dev-2', created_at: daysAgo(7), merged_at: daysAgo(3) },
  { id: 'br-5', project_id: 'proj-1', repo_id: 'repo-1', branch_name: 'feature/REQ-003-admin-list', source_type: 'requirement', source_id: 'req-3', base_branch: 'main', status: 'active', created_by: 'dev-1', created_at: daysAgo(5) },
  { id: 'br-6', project_id: 'proj-2', repo_id: 'repo-2', branch_name: 'feature/REQ-007-auth-middleware', source_type: 'requirement', source_id: 'req-7', base_branch: 'main', status: 'active', created_by: 'dev-3', created_at: daysAgo(12) },
]

// ── 演示提交记录 ──────────────────────────────────────────────
export const demoCommits = [
  { id: 'cm-1', branch_id: 'br-1', commit_hash: 'a1b2c3d4e5f6789012345678901234567890abcd', author_name: '张伟', author_email: 'zhangwei@example.com', message: 'feat: 实现反馈表单页面布局和表单组件\n\n- 添加反馈类型选择器（Bug/建议/咨询/投诉）\n- 实现表单前端校验（必填项、字数限制、图片格式）\n- 接入 Element Plus 表单组件', files_changed: 6, additions: 342, deletions: 12, committed_at: daysAgo(10) },
  { id: 'cm-2', branch_id: 'br-1', commit_hash: 'b2c3d4e5f6789012345678901234567890abcde1', author_name: '张伟', author_email: 'zhangwei@example.com', message: 'feat: 添加图片上传组件和预览功能', files_changed: 3, additions: 156, deletions: 8, committed_at: daysAgo(5) },
  { id: 'cm-3', branch_id: 'br-2', commit_hash: 'c3d4e5f6789012345678901234567890abcde12a', author_name: '李娜', author_email: 'lina@example.com', message: 'feat: 实现反馈数据 CRUD API\n\n- POST /api/feedback 创建反馈\n- GET /api/feedback 分页查询（支持类型/状态筛选）\n- GET /api/feedback/:id 单条详情\n- PATCH /api/feedback/:id 更新状态', files_changed: 5, additions: 278, deletions: 3, committed_at: daysAgo(9) },
  { id: 'cm-4', branch_id: 'br-2', commit_hash: 'd4e5f6789012345678901234567890abcde123b', author_name: '李娜', author_email: 'lina@example.com', message: 'fix: 修复反馈内容字段长度限制\n\n- 数据库字段从 VARCHAR(1000) 改为 TEXT\n- 添加 API 层的字符数校验（最大 5000）', files_changed: 2, additions: 15, deletions: 3, committed_at: daysAgo(4) },
  { id: 'cm-5', branch_id: 'br-3', commit_hash: 'e5f6789012345678901234567890abcde1234c5', author_name: '张伟', author_email: 'zhangwei@example.com', message: 'fix: 修复 Safari 下提交按钮事件绑定问题\n\n- 原因：Safari 对 click 事件在 button[type=submit] 上的处理与 Chrome 不同\n- 修复：改用 form submit 事件 + @submit.prevent', files_changed: 1, additions: 8, deletions: 3, committed_at: daysAgo(3) },
]

// ── 演示代码仓库 ──────────────────────────────────────────────
export const demoRepos = [
  {
    id: 'repo-1',
    project_id: 'proj-1',
    name: 'feedback-system',
    description: '用户反馈系统主仓库',
    repo_url: 'https://github.com/example/feedback-system',
    default_branch: 'main',
    language: 'Vue + Python',
    is_local: true,
    status: 'active',
    created_at: daysAgo(30),
    updated_at: daysAgo(0.5),
    branches: [
      { name: 'main', last_commit: 'c3d4e5f', last_commit_msg: 'feat: 实现反馈数据 CRUD API', last_commit_time: daysAgo(4), author: '李娜' },
      { name: 'feature/REQ-001-feedback-form', last_commit: 'b2c3d4e', last_commit_msg: 'feat: 添加图片上传组件和预览功能', last_commit_time: daysAgo(5), author: '张伟' },
      { name: 'feature/REQ-002-feedback-api', last_commit: 'd4e5f67', last_commit_msg: 'fix: 修复反馈内容字段长度限制', last_commit_time: daysAgo(4), author: '李娜' },
      { name: 'fix/BUG-001-safari-submit', last_commit: 'e5f6789', last_commit_msg: 'fix: 修复 Safari 下提交按钮事件绑定问题', last_commit_time: daysAgo(3), author: '张伟' },
      { name: 'fix/BUG-002-content-length', last_commit: 'd4e5f67', last_commit_msg: 'fix: 修复反馈内容字段长度限制', last_commit_time: daysAgo(4), author: '李娜' },
    ],
  },
  {
    id: 'repo-2',
    project_id: 'proj-1',
    name: 'feedback-docs',
    description: '项目文档仓库',
    repo_url: 'https://github.com/example/feedback-docs',
    default_branch: 'main',
    language: 'Markdown',
    is_local: true,
    status: 'active',
    created_at: daysAgo(28),
    updated_at: daysAgo(10),
    branches: [
      { name: 'main', last_commit: 'abcd123', last_commit_msg: 'docs: 更新 API 文档', last_commit_time: daysAgo(10), author: '王磊' },
    ],
  },
]

// ── 演示代码文件树 ────────────────────────────────────────────
export const demoFileTree = [
  {
    id: 'f-1', name: 'frontend', file_type: 'directory', file_path: 'frontend', children: [
      { id: 'f-1-1', name: 'src', file_type: 'directory', file_path: 'frontend/src', children: [
        { id: 'f-1-1-1', name: 'components', file_type: 'directory', file_path: 'frontend/src/components', children: [
          { id: 'f-1-1-1-1', name: 'FeedbackForm.vue', file_type: 'file', file_path: 'frontend/src/components/FeedbackForm.vue', extension: '.vue', size: 12300 },
          { id: 'f-1-1-1-2', name: 'FeedbackList.vue', file_type: 'file', file_path: 'frontend/src/components/FeedbackList.vue', extension: '.vue', size: 8900 },
          { id: 'f-1-1-1-3', name: 'AdminTable.vue', file_type: 'file', file_path: 'frontend/src/components/AdminTable.vue', extension: '.vue', size: 5600 },
        ]},
        { id: 'f-1-1-2', name: 'App.vue', file_type: 'file', file_path: 'frontend/src/App.vue', extension: '.vue', size: 1200 },
        { id: 'f-1-1-3', name: 'main.js', file_type: 'file', file_path: 'frontend/src/main.js', extension: '.js', size: 450 },
      ]},
      { id: 'f-1-2', name: 'package.json', file_type: 'file', file_path: 'frontend/package.json', extension: '.json', size: 1800 },
    ],
  },
  {
    id: 'f-2', name: 'backend', file_type: 'directory', file_path: 'backend', children: [
      { id: 'f-2-1', name: 'app.py', file_type: 'file', file_path: 'backend/app.py', extension: '.py', size: 2300 },
      { id: 'f-2-2', name: 'models.py', file_type: 'file', file_path: 'backend/models.py', extension: '.py', size: 3400 },
      { id: 'f-2-3', name: 'routes.py', file_type: 'file', file_path: 'backend/routes.py', extension: '.py', size: 5100 },
      { id: 'f-2-4', name: 'requirements.txt', file_type: 'file', file_path: 'backend/requirements.txt', extension: '.txt', size: 230 },
    ],
  },
  { id: 'f-3', name: 'README.md', file_type: 'file', file_path: 'README.md', extension: '.md', size: 3200 },
  { id: 'f-4', name: 'docker-compose.yml', file_type: 'file', file_path: 'docker-compose.yml', extension: '.yml', size: 890 },
]

// ── 演示文件内容 ──────────────────────────────────────────────
export const demoFileContent = {
  'frontend/src/components/FeedbackForm.vue': `<template>
  <div class="feedback-form">
    <h2>提交反馈</h2>
    <el-form :model="form" :rules="rules" ref="formRef" label-width="100px">
      <el-form-item label="反馈类型" prop="type">
        <el-select v-model="form.type" placeholder="请选择反馈类型">
          <el-option label="Bug 反馈" value="bug" />
          <el-option label="功能建议" value="suggestion" />
          <el-option label="咨询问题" value="consult" />
          <el-option label="投诉" value="complaint" />
        </el-select>
      </el-form-item>
      <el-form-item label="反馈内容" prop="content">
        <el-input v-model="form.content" type="textarea" :rows="5"
          placeholder="请详细描述您遇到的问题或建议..." maxlength="5000" show-word-limit />
      </el-form-item>
      <el-form-item label="联系方式" prop="contact">
        <el-input v-model="form.contact" placeholder="邮箱或手机号（选填）" />
      </el-form-item>
      <el-form-item>
        <el-button type="primary" @click="submitForm">提交反馈</el-button>
      </el-form-item>
    </el-form>
  </div>
</template>`,
  'backend/routes.py': `from flask import Blueprint, request, jsonify
from models import Feedback
from middleware import jwt_required

api = Blueprint('api', __name__)

@api.route('/api/feedback', methods=['POST'])
def create_feedback():
    """创建反馈"""
    data = request.get_json()
    feedback = Feedback(
        type=data.get('type'),
        content=data.get('content'),
        contact=data.get('contact', '')
    )
    db.session.add(feedback)
    db.session.commit()
    return jsonify({"code": 201, "data": feedback.to_dict()})

@api.route('/api/feedback', methods=['GET'])
@jwt_required
def list_feedback():
    """分页查询反馈列表"""
    page = request.args.get('page', 1, type=int)
    per_page = request.args.get('per_page', 20, type=int)
    feedback_type = request.args.get('type')
    status = request.args.get('status')
    # ... 筛选和分页逻辑
    return jsonify({"code": 200, "data": {"items": [...], "total": 45}})
`,
}

// ── 演示代码审查 ──────────────────────────────────────────────
export const demoReviews = [
  {
    id: 'rv-1',
    project_id: 'proj-1',
    repo_id: 'repo-1',
    title: '审查：反馈表单组件 (FeedbackForm.vue)',
    code_content: null,
    file_paths: ['frontend/src/components/FeedbackForm.vue'],
    language: 'Vue',
    status: 'completed',
    summary: '代码整体质量良好，发现 1 个严重问题、3 个警告、2 个建议。安全问题已修复，规范问题需要改进。',
    score: 8.2,
    scores: { security: 8.5, style: 7.0, logic: 9.0, performance: 6.5 },
    created_at: daysAgo(5),
    issues: [
      { id: 'is-1', severity: 'critical', category: 'security', file_name: 'FeedbackForm.vue', line_number: 42, title: 'XSS 漏洞：用户输入未做转义', description: 'v-html 直接渲染用户输入内容可能导致 XSS 攻击', suggestion: '使用 {{ }} 插值代替 v-html，或在渲染前使用 DOMPurify 过滤', code_snippet: '<div v-html="userContent"></div>', fixed_snippet: '<div>{{ userContent }}</div>' },
      { id: 'is-2', severity: 'warning', category: 'style', file_name: 'FeedbackForm.vue', line_number: 15, title: '组件命名不符合 Vue 规范', description: '组件名应使用多词组合避免与 HTML 元素冲突', suggestion: '建议重命名为 FeedbackFormPanel 或 AppFeedbackForm' },
      { id: 'is-3', severity: 'warning', category: 'performance', file_name: 'FeedbackForm.vue', line_number: 68, title: '大列表未使用虚拟滚动', description: '反馈列表在数据量大时渲染性能差', suggestion: '使用 el-table 的虚拟滚动或分页加载' },
      { id: 'is-4', severity: 'warning', category: 'logic', file_name: 'FeedbackForm.vue', line_number: 89, title: '缺少网络异常处理', description: 'API 调用未处理网络超时和断网情况', suggestion: '添加 try-catch 和用户友好的错误提示' },
      { id: 'is-5', severity: 'info', category: 'style', file_name: 'FeedbackForm.vue', line_number: 120, title: '建议提取魔法数字为常量', description: 'maxlength="5000" 硬编码在模板中', suggestion: '定义常量 MAX_CONTENT_LENGTH = 5000 并引用' },
      { id: 'is-6', severity: 'info', category: 'performance', file_name: 'FeedbackForm.vue', line_number: 55, title: '图片上传未压缩', description: '用户上传的原图可能很大导致加载慢', suggestion: '上传前使用 Canvas 压缩图片到合理尺寸（最大 1920px）' },
    ],
  },
  {
    id: 'rv-2',
    project_id: 'proj-1',
    repo_id: 'repo-1',
    title: '审查：反馈数据 API (routes.py)',
    code_content: null,
    file_paths: ['backend/routes.py', 'backend/models.py'],
    language: 'Python',
    status: 'completed',
    summary: 'API 设计规范，逻辑清晰。发现 1 个警告和 1 个建议。主要关注 SQL 注入防护和输入校验。',
    score: 8.8,
    scores: { security: 9.0, style: 8.5, logic: 9.5, performance: 8.0 },
    created_at: daysAgo(3),
    issues: [
      { id: 'is-7', severity: 'warning', category: 'security', file_name: 'routes.py', line_number: 34, title: '缺少输入长度校验', description: 'API 层未对 content 字段做长度校验，依赖数据库层限制', suggestion: '在路由中添加 if len(content) > 5000: return error' },
      { id: 'is-8', severity: 'info', category: 'performance', file_name: 'routes.py', line_number: 22, title: '建议添加数据库索引', description: 'feedback 表缺少 type + status 的复合索引', suggestion: 'CREATE INDEX idx_type_status ON feedback(type, status)' },
    ],
  },
  {
    id: 'rv-3',
    project_id: 'proj-1',
    repo_id: 'repo-1',
    title: '审查：Safari 兼容性修复',
    code_content: null,
    file_paths: ['frontend/src/components/FeedbackForm.vue'],
    language: 'Vue',
    status: 'reviewing',
    summary: null,
    score: null,
    scores: null,
    created_at: daysAgo(0.5),
    issues: [],
  },
]

// ── 演示构建记录 ──────────────────────────────────────────────
export const demoBuilds = [
  {
    id: 'bld-1',
    project_id: 'proj-1',
    build_number: 42,
    build_type: 'push',
    status: 'success',
    commit_hash: 'a1b2c3d4e5f6789012345678901234567890abcd',
    commit_message: 'feat: 实现反馈表单页面布局和表单组件',
    branch: 'feature/REQ-001-feedback-form',
    started_at: daysAgo(10),
    finished_at: new Date(new Date(daysAgo(10)).getTime() + 3 * 60 * 1000).toISOString(),
    duration_seconds: 180,
    created_by: '张伟',
    steps: [
      { step_name: '环境准备', step_order: 1, status: 'success', command: 'npm ci', duration_seconds: 35 },
      { step_name: '代码检查', step_order: 2, status: 'success', command: 'npm run lint', duration_seconds: 22 },
      { step_name: '单元测试', step_order: 3, status: 'success', command: 'npm run test:unit', duration_seconds: 68, log: 'Tests: 45 passed, 45 total\nCoverage: 87.3% statements, 82.1% branches, 90.5% functions' },
      { step_name: '构建打包', step_order: 4, status: 'success', command: 'npm run build', duration_seconds: 55 },
    ],
    preview_url: 'https://preview-f42.example.com/feedback-system',
    artifacts: ['dist/feedback-system.zip', 'dist/index.html', 'Dockerfile'],
  },
  {
    id: 'bld-2',
    project_id: 'proj-1',
    build_number: 43,
    build_type: 'push',
    status: 'failed',
    commit_hash: 'c3d4e5f6789012345678901234567890abcde12a',
    commit_message: 'feat: 实现反馈数据 CRUD API',
    branch: 'feature/REQ-002-feedback-api',
    started_at: daysAgo(9),
    finished_at: new Date(new Date(daysAgo(9)).getTime() + 2 * 60 * 1000).toISOString(),
    duration_seconds: 120,
    created_by: '李娜',
    error_summary: '单元测试失败：test_create_feedback 断言错误，期望 201 实际 500',
    steps: [
      { step_name: '环境准备', step_order: 1, status: 'success', command: 'pip install -r requirements.txt', duration_seconds: 28 },
      { step_name: '代码检查', step_order: 2, status: 'success', command: 'flake8 backend/', duration_seconds: 12 },
      { step_name: '单元测试', step_order: 3, status: 'failed', command: 'pytest tests/', duration_seconds: 45, log: 'FAILED tests/test_feedback.py::test_create_feedback - AssertionError: Expected 201, got 500\nFAILED tests/test_feedback.py::test_list_feedback_pagination - AssertionError...\n2 failed, 12 passed in 12.34s' },
      { step_name: '构建打包', step_order: 4, status: 'skipped', command: 'docker build -t feedback-api .', duration_seconds: 0 },
    ],
    artifacts: [],
  },
  {
    id: 'bld-3',
    project_id: 'proj-1',
    build_number: 44,
    build_type: 'push',
    status: 'success',
    commit_hash: 'd4e5f6789012345678901234567890abcde123b',
    commit_message: 'fix: 修复反馈内容字段长度限制',
    branch: 'feature/REQ-002-feedback-api',
    started_at: daysAgo(4),
    finished_at: new Date(new Date(daysAgo(4)).getTime() + 2.5 * 60 * 1000).toISOString(),
    duration_seconds: 150,
    created_by: '李娜',
    steps: [
      { step_name: '环境准备', step_order: 1, status: 'success', command: 'pip install -r requirements.txt', duration_seconds: 25 },
      { step_name: '代码检查', step_order: 2, status: 'success', command: 'flake8 backend/', duration_seconds: 11 },
      { step_name: '单元测试', step_order: 3, status: 'success', command: 'pytest tests/', duration_seconds: 52, log: '14 passed in 8.21s\nCoverage: 91.2%' },
      { step_name: '构建打包', step_order: 4, status: 'success', command: 'docker build -t feedback-api .', duration_seconds: 42 },
      { step_name: '部署预览', step_order: 5, status: 'success', command: 'docker-compose up -d', duration_seconds: 20 },
    ],
    preview_url: 'https://preview-d4e.example.com/feedback-system',
    artifacts: ['dist/feedback-api.tar.gz', 'Dockerfile', 'docker-compose.yml'],
  },
]

// ── 演示活动日志 ──────────────────────────────────────────────
export const demoActivities = [
  { id: 'act-1', target_type: 'requirement', target_id: 'req-1', action: 'created', detail: { title: '反馈提交表单页面' }, user_id: 'dev-1', user_name: '张伟', created_at: daysAgo(14) },
  { id: 'act-2', target_type: 'requirement', target_id: 'req-1', action: 'assigned', detail: { assignee: '张伟', role: 'primary' }, user_id: 'dev-1', user_name: '张伟', created_at: daysAgo(14) },
  { id: 'act-3', target_type: 'requirement', target_id: 'req-1', action: 'status_changed', detail: { from: 'todo', to: 'in_progress' }, user_id: 'dev-1', user_name: '张伟', created_at: daysAgo(12) },
  { id: 'act-4', target_type: 'requirement', target_id: 'req-2', action: 'created', detail: { title: '反馈数据 API' }, user_id: 'dev-2', user_name: '李娜', created_at: daysAgo(14) },
  { id: 'act-5', target_type: 'requirement', target_id: 'req-2', action: 'assigned', detail: { assignee: '李娜', role: 'primary' }, user_id: 'dev-2', user_name: '李娜', created_at: daysAgo(14) },
  { id: 'act-6', target_type: 'requirement', target_id: 'req-2', action: 'status_changed', detail: { from: 'todo', to: 'in_progress' }, user_id: 'dev-2', user_name: '李娜', created_at: daysAgo(13) },
  { id: 'act-7', target_type: 'requirement', target_id: 'req-3', action: 'created', detail: { title: '管理员反馈列表页' }, user_id: 'dev-1', user_name: '张伟', created_at: daysAgo(12) },
  { id: 'act-8', target_type: 'requirement', target_id: 'req-3', action: 'assigned', detail: { assignee: '张伟', role: 'primary' }, user_id: 'dev-1', user_name: '张伟', created_at: daysAgo(12) },
  { id: 'act-9', target_type: 'requirement', target_id: 'req-1', action: 'status_changed', detail: { from: 'in_progress', to: 'in_review' }, user_id: 'dev-1', user_name: '张伟', created_at: daysAgo(2) },
  { id: 'act-10', target_type: 'bug', target_id: 'bug-1', action: 'created', detail: { title: '反馈提交按钮在 Safari 下点击无响应' }, user_id: 'dev-6', user_name: '刘洋', created_at: daysAgo(5) },
  { id: 'act-11', target_type: 'bug', target_id: 'bug-1', action: 'assigned', detail: { assignee: '张伟', role: 'fixer' }, user_id: 'dev-6', user_name: '刘洋', created_at: daysAgo(5) },
  { id: 'act-12', target_type: 'bug', target_id: 'bug-1', action: 'status_changed', detail: { from: 'open', to: 'in_progress' }, user_id: 'dev-1', user_name: '张伟', created_at: daysAgo(4) },
  { id: 'act-13', target_type: 'bug', target_id: 'bug-2', action: 'created', detail: { title: '反馈内容超过 1000 字时 API 返回 500' }, user_id: 'dev-6', user_name: '刘洋', created_at: daysAgo(8) },
  { id: 'act-14', target_type: 'bug', target_id: 'bug-2', action: 'assigned', detail: { assignee: '李娜', role: 'fixer' }, user_id: 'dev-6', user_name: '刘洋', created_at: daysAgo(8) },
  { id: 'act-15', target_type: 'bug', target_id: 'bug-2', action: 'status_changed', detail: { from: 'open', to: 'in_progress' }, user_id: 'dev-2', user_name: '李娜', created_at: daysAgo(7) },
  { id: 'act-16', target_type: 'bug', target_id: 'bug-2', action: 'status_changed', detail: { from: 'in_progress', to: 'fixed' }, user_id: 'dev-2', user_name: '李娜', created_at: daysAgo(3) },
  { id: 'act-17', target_type: 'requirement', target_id: 'req-1', action: 'commented', detail: { comment_id: 'comment-1' }, user_id: 'dev-1', user_name: '张伟', created_at: daysAgo(10) },
  { id: 'act-18', target_type: 'requirement', target_id: 'req-2', action: 'commented', detail: { comment_id: 'comment-6' }, user_id: 'dev-2', user_name: '李娜', created_at: daysAgo(12) },
  { id: 'act-19', target_type: 'bug', target_id: 'bug-1', action: 'commented', detail: { comment_id: 'comment-13' }, user_id: 'dev-1', user_name: '张伟', created_at: daysAgo(3) },
  { id: 'act-20', target_type: 'bug', target_id: 'bug-2', action: 'commented', detail: { comment_id: 'comment-16' }, user_id: 'dev-2', user_name: '李娜', created_at: daysAgo(5) },
  { id: 'act-21', target_type: 'requirement', target_id: 'req-7', action: 'created', detail: { title: '统一认证鉴权中间件' }, user_id: 'dev-3', user_name: '王磊', created_at: daysAgo(14) },
  { id: 'act-22', target_type: 'requirement', target_id: 'req-7', action: 'commented', detail: { comment_id: 'comment-10' }, user_id: 'dev-3', user_name: '王磊', created_at: daysAgo(12) },
  { id: 'act-23', target_type: 'bug', target_id: 'bug-3', action: 'created', detail: { title: '管理员列表页分页切换后筛选条件丢失' }, user_id: 'dev-6', user_name: '刘洋', created_at: daysAgo(3) },
  { id: 'act-24', target_type: 'bug', target_id: 'bug-5', action: 'created', detail: { title: 'JWT Token 过期后前端未自动刷新导致请求失败' }, user_id: 'dev-6', user_name: '刘洋', created_at: daysAgo(4) },
  { id: 'act-25', target_type: 'bug', target_id: 'bug-5', action: 'status_changed', detail: { from: 'open', to: 'confirmed' }, user_id: 'dev-3', user_name: '王磊', created_at: daysAgo(3) },
]

// ── 聚合导出 ──────────────────────────────────────────────────
export default {
  developers,
  demoProjects,
  demoIterations,
  demoRequirements,
  demoBugs,
  demoComments,
  demoActivities,
  demoBranches,
  demoCommits,
  demoRepos,
  demoFileTree,
  demoFileContent,
  demoReviews,
  demoBuilds,
}
