import axios from './axios'

const root = '/domain/office'

export const listMeetings = params => axios.get(`${root}/meetings`, { params })
export const createMeeting = data => axios.post(`${root}/meetings`, data)
export const updateMeeting = (id, data) => axios.put(`${root}/meetings/${id}`, data)
export const deleteMeeting = id => axios.delete(`${root}/meetings/${id}`)
export const getMeeting = id => axios.get(`${root}/meetings/${id}`)
export const createActionItem = (meetingId, data) => axios.post(`${root}/meetings/${meetingId}/action-items`, data)
export const updateActionItem = (id, data) => axios.put(`${root}/meetings/action-items/${id}`, data)
export const listSchedules = params => axios.get(`${root}/schedules`, { params })
export const createSchedule = data => axios.post(`${root}/schedules`, data)
export const updateSchedule = (id, data) => axios.put(`${root}/schedules/${id}`, data)
export const getDashboard = workspaceId => axios.get(`${root}/dashboard/summary`, { params: { workspace_id: workspaceId } })
export const listDocuments = params => axios.get(`${root}/documents`, { params })
export const getDocument = id => axios.get(`${root}/documents/${id}`)
export const createDocument = data => axios.post(`${root}/documents`, data)
export const submitDocument = (id, data) => axios.post(`${root}/documents/${id}/submit`, data)
export const publishDocument = id => axios.post(`${root}/documents/${id}/publish`)
export const confirmDocumentReceipt = id => axios.post(`${root}/documents/${id}/confirm-receipt`)
export const listApprovals = params => axios.get(`${root}/approvals`, { params })
export const getApproval = id => axios.get(`${root}/approvals/${id}`)
export const generateMeetingDraft = data => axios.post('/office-ai/meeting-draft', data)
export const generateDocumentDraft = data => axios.post('/office-ai/document-draft', data)
export const generateWeeklyDraft = data => axios.post('/office-ai/weekly-draft', data)
export const approveApproval = (id, data) => axios.post(`${root}/approvals/${id}/approve`, data)
export const rejectApproval = (id, data) => axios.post(`${root}/approvals/${id}/reject`, data)
export const getOrganization = workspaceId => axios.get(`${root}/organization`, { params: { workspace_id: workspaceId } })
export const bootstrapOrganization = data => axios.post(`${root}/organization/bootstrap`, data)
export const createGroup = data => axios.post(`${root}/organization/groups`, data)
export const addMember = data => axios.post(`${root}/organization/members`, data)
export const updateMember = (id, data) => axios.put(`${root}/organization/members/${id}`, data)
export const searchUsers = query => axios.get('/user-directory', { params: { query } })
export const listNotifications = workspaceId => axios.get(`${root}/organization/notifications`, { params: { workspace_id: workspaceId } })
export const readNotification = id => axios.post(`${root}/organization/notifications/${id}/read`)
export const grantWorkspaceMember = (workspaceId, userId) => axios.post(`/workspaces/${workspaceId}/members`, { user_id: userId })
export const listTemplates = params => axios.get(`${root}/document-templates`, { params })
export const createTemplate = data => axios.post(`${root}/document-templates`, data)
export const updateTemplate = (id, data) => axios.put(`${root}/document-templates/${id}`, data)
export const deleteTemplate = id => axios.delete(`${root}/document-templates/${id}`)
