"""Office/PDF adapters for durable Education content versions.

The editable JSON remains authoritative. These adapters create portable files
on demand without placing generated bytes in a sandbox or treating an Office
file as the source of truth.
"""

from io import BytesIO
from html import escape
import re


class ContentExportError(RuntimeError):
    pass


MIME_TYPES = {
    "pptx": (
        "application/vnd.openxmlformats-officedocument.presentationml.presentation"
    ),
    "docx": (
        "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
    ),
    "pdf": "application/pdf",
}


def _plain_text(value):
    if value is None:
        return ""
    if isinstance(value, str):
        return re.sub(r"\s+", " ", re.sub(r"<[^>]+>", " ", value)).strip()
    if isinstance(value, (int, float, bool)):
        return str(value)
    if isinstance(value, list):
        return "\n".join(filter(None, (_plain_text(item) for item in value)))
    if isinstance(value, dict):
        preferred = (
            "content",
            "text",
            "description",
            "label",
            "name",
            "title",
            "prompt",
        )
        selected = [
            _plain_text(value[key])
            for key in preferred
            if key in value and _plain_text(value[key])
        ]
        if selected:
            return "\n".join(selected)
        return "\n".join(
            f"{str(key).replace('_', ' ')}：{_plain_text(item)}"
            for key, item in value.items()
            if _plain_text(item)
        )
    return str(value)


def _content_title(source, fallback):
    if isinstance(source, dict):
        for key in ("title", "lesson_title", "name"):
            value = _plain_text(source.get(key))
            if value:
                return value[:200]
    return str(fallback or "WeAgent Education 课件")[:200]


def _slide_records(source, fallback_title):
    title = _content_title(source, fallback_title)
    if isinstance(source, dict) and isinstance(source.get("slides"), list):
        slides = []
        for index, item in enumerate(source["slides"][:100], 1):
            if not isinstance(item, dict):
                slides.append(
                    {"title": f"第 {index} 页", "lines": [_plain_text(item)]}
                )
                continue
            slide_title = _plain_text(item.get("title")) or f"第 {index} 页"
            blocks = item.get("blocks")
            if not isinstance(blocks, list):
                blocks = [
                    value
                    for key, value in item.items()
                    if key not in {"id", "title", "layout", "speaker_notes"}
                ]
            lines = []
            for block in blocks[:40]:
                text = _plain_text(block)
                if text:
                    lines.extend(part for part in text.splitlines() if part.strip())
            slides.append(
                {
                    "title": slide_title[:200],
                    "lines": lines[:40] or ["（本页暂无正文）"],
                    "notes": _plain_text(item.get("speaker_notes")),
                }
            )
        return title, slides

    slides = []
    if isinstance(source, dict):
        objectives = source.get("objectives")
        if isinstance(objectives, list) and objectives:
            slides.append(
                {
                    "title": "教学目标",
                    "lines": [_plain_text(item) for item in objectives if _plain_text(item)],
                }
            )
        stages = source.get("stages")
        if isinstance(stages, list):
            for index, stage in enumerate(stages[:30], 1):
                stage_title = (
                    _plain_text(stage.get("name"))
                    if isinstance(stage, dict)
                    else ""
                ) or f"教学活动 {index}"
                lines = []
                if isinstance(stage, dict):
                    for key, label in (
                        ("duration_minutes", "时间"),
                        ("description", "活动"),
                        ("teacher_activity", "教师活动"),
                        ("student_activity", "学生活动"),
                        ("assessment", "评价"),
                    ):
                        value = _plain_text(stage.get(key))
                        if value:
                            suffix = " 分钟" if key == "duration_minutes" else ""
                            lines.append(f"{label}：{value}{suffix}")
                else:
                    lines.append(_plain_text(stage))
                slides.append({"title": stage_title[:200], "lines": lines})
        consumed = {"title", "lesson_title", "name", "objectives", "stages"}
        for key, value in list(source.items())[:50]:
            if key in consumed or key.endswith("_code"):
                continue
            text = _plain_text(value)
            if text:
                slides.append(
                    {
                        "title": str(key).replace("_", " ").title()[:200],
                        "lines": text.splitlines()[:40],
                    }
                )
    if not slides:
        slides = [{"title": "内容", "lines": [_plain_text(source) or "（暂无正文）"]}]
    return title, slides[:100]


def export_pptx(source, fallback_title):
    try:
        from pptx import Presentation
        from pptx.dml.color import RGBColor
        from pptx.enum.text import PP_ALIGN
        from pptx.util import Inches, Pt
    except ImportError as exc:
        raise ContentExportError("python-pptx adapter is unavailable") from exc

    title, slides = _slide_records(source, fallback_title)
    presentation = Presentation()
    presentation.slide_width = Inches(13.333)
    presentation.slide_height = Inches(7.5)
    blank_layout = presentation.slide_layouts[6]

    cover = presentation.slides.add_slide(blank_layout)
    cover.background.fill.solid()
    cover.background.fill.fore_color.rgb = RGBColor(22, 48, 45)
    accent = cover.shapes.add_shape(
        1, Inches(0.75), Inches(1.05), Inches(0.14), Inches(4.8)
    )
    accent.fill.solid()
    accent.fill.fore_color.rgb = RGBColor(52, 174, 153)
    accent.line.fill.background()
    title_box = cover.shapes.add_textbox(
        Inches(1.2), Inches(1.35), Inches(10.9), Inches(2.1)
    )
    title_frame = title_box.text_frame
    title_frame.clear()
    title_run = title_frame.paragraphs[0].add_run()
    title_run.text = title
    title_run.font.name = "Microsoft YaHei"
    title_run.font.size = Pt(30)
    title_run.font.bold = True
    title_run.font.color.rgb = RGBColor(244, 250, 248)
    subtitle = cover.shapes.add_textbox(
        Inches(1.22), Inches(4.35), Inches(9), Inches(0.7)
    )
    subtitle_frame = subtitle.text_frame
    subtitle_frame.text = "WeAgent Education · 可编辑课件"
    subtitle_frame.paragraphs[0].runs[0].font.name = "Microsoft YaHei"
    subtitle_frame.paragraphs[0].runs[0].font.size = Pt(14)
    subtitle_frame.paragraphs[0].runs[0].font.color.rgb = RGBColor(151, 207, 197)

    for index, record in enumerate(slides, 1):
        slide = presentation.slides.add_slide(blank_layout)
        slide.background.fill.solid()
        slide.background.fill.fore_color.rgb = RGBColor(248, 251, 250)
        header = slide.shapes.add_textbox(
            Inches(0.8), Inches(0.58), Inches(11.7), Inches(0.8)
        )
        header_frame = header.text_frame
        header_frame.clear()
        header_run = header_frame.paragraphs[0].add_run()
        header_run.text = record["title"]
        header_run.font.name = "Microsoft YaHei"
        header_run.font.size = Pt(24)
        header_run.font.bold = True
        header_run.font.color.rgb = RGBColor(35, 70, 64)
        rule = slide.shapes.add_shape(
            1, Inches(0.82), Inches(1.48), Inches(1.15), Inches(0.06)
        )
        rule.fill.solid()
        rule.fill.fore_color.rgb = RGBColor(45, 145, 130)
        rule.line.fill.background()

        body = slide.shapes.add_textbox(
            Inches(0.92), Inches(1.72), Inches(11.45), Inches(4.85)
        )
        frame = body.text_frame
        frame.word_wrap = True
        frame.clear()
        for line_index, line in enumerate(record.get("lines") or ["（暂无正文）"]):
            paragraph = frame.paragraphs[0] if line_index == 0 else frame.add_paragraph()
            paragraph.text = str(line)[:1200]
            paragraph.level = 0
            paragraph.space_after = Pt(8)
            paragraph.font.name = "Microsoft YaHei"
            paragraph.font.size = Pt(17 if len(record.get("lines") or []) <= 8 else 14)
            paragraph.font.color.rgb = RGBColor(61, 78, 74)

        page = slide.shapes.add_textbox(
            Inches(11.7), Inches(6.88), Inches(0.7), Inches(0.3)
        )
        page_frame = page.text_frame
        page_frame.text = f"{index:02d}"
        page_frame.paragraphs[0].alignment = PP_ALIGN.RIGHT
        page_frame.paragraphs[0].runs[0].font.size = Pt(9)
        page_frame.paragraphs[0].runs[0].font.color.rgb = RGBColor(108, 145, 138)

    stream = BytesIO()
    presentation.save(stream)
    return stream.getvalue()


def export_docx(source, fallback_title):
    try:
        from docx import Document
        from docx.enum.text import WD_ALIGN_PARAGRAPH
        from docx.oxml.ns import qn
        from docx.shared import Pt, RGBColor
    except ImportError as exc:
        raise ContentExportError("python-docx adapter is unavailable") from exc

    title, slides = _slide_records(source, fallback_title)
    document = Document()
    normal = document.styles["Normal"]
    normal.font.name = "Microsoft YaHei"
    normal._element.rPr.rFonts.set(qn("w:eastAsia"), "Microsoft YaHei")
    normal.font.size = Pt(10.5)

    heading = document.add_heading(title, level=0)
    heading.alignment = WD_ALIGN_PARAGRAPH.CENTER
    for run in heading.runs:
        run.font.name = "Microsoft YaHei"
        run._element.rPr.rFonts.set(qn("w:eastAsia"), "Microsoft YaHei")
        run.font.color.rgb = RGBColor(31, 93, 84)
    meta = document.add_paragraph("WeAgent Education · 可编辑内容导出")
    meta.alignment = WD_ALIGN_PARAGRAPH.CENTER

    for record in slides:
        document.add_heading(record["title"], level=1)
        for line in record.get("lines") or ["（暂无正文）"]:
            document.add_paragraph(str(line)[:4000], style="List Bullet")
        if record.get("notes"):
            document.add_heading("讲者备注", level=2)
            document.add_paragraph(record["notes"][:8000])

    stream = BytesIO()
    document.save(stream)
    return stream.getvalue()


def export_pdf(source, fallback_title):
    try:
        from reportlab.lib.enums import TA_CENTER
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
        from reportlab.lib.units import mm
        from reportlab.pdfbase import pdfmetrics
        from reportlab.pdfbase.cidfonts import UnicodeCIDFont
        from reportlab.platypus import (
            PageBreak,
            Paragraph,
            SimpleDocTemplate,
            Spacer,
        )
    except ImportError as exc:
        raise ContentExportError("ReportLab adapter is unavailable") from exc

    title, slides = _slide_records(source, fallback_title)
    try:
        pdfmetrics.registerFont(UnicodeCIDFont("STSong-Light"))
    except Exception as exc:
        raise ContentExportError("CJK PDF font adapter is unavailable") from exc

    stream = BytesIO()
    document = SimpleDocTemplate(
        stream,
        pagesize=A4,
        rightMargin=18 * mm,
        leftMargin=18 * mm,
        topMargin=18 * mm,
        bottomMargin=18 * mm,
        title=title,
    )
    sample = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "EducationTitle",
        parent=sample["Title"],
        fontName="STSong-Light",
        fontSize=22,
        leading=31,
        textColor="#1f5d54",
        alignment=TA_CENTER,
        spaceAfter=16,
    )
    subtitle_style = ParagraphStyle(
        "EducationSubtitle",
        parent=sample["BodyText"],
        fontName="STSong-Light",
        fontSize=10,
        leading=16,
        textColor="#71827e",
        alignment=TA_CENTER,
    )
    heading_style = ParagraphStyle(
        "EducationHeading",
        parent=sample["Heading1"],
        fontName="STSong-Light",
        fontSize=16,
        leading=23,
        textColor="#245f56",
        spaceAfter=10,
    )
    body_style = ParagraphStyle(
        "EducationBody",
        parent=sample["BodyText"],
        fontName="STSong-Light",
        fontSize=10.5,
        leading=18,
        textColor="#344641",
        leftIndent=5 * mm,
        firstLineIndent=-3 * mm,
        spaceAfter=6,
    )
    story = [
        Spacer(1, 42 * mm),
        Paragraph(escape(title), title_style),
        Paragraph("WeAgent Education · PDF 导出", subtitle_style),
        PageBreak(),
    ]
    for index, record in enumerate(slides):
        story.append(Paragraph(escape(record["title"]), heading_style))
        for line in record.get("lines") or ["（暂无正文）"]:
            story.append(Paragraph(f"• {escape(str(line)[:4000])}", body_style))
        if record.get("notes"):
            story.append(Spacer(1, 3 * mm))
            story.append(
                Paragraph(f"讲者备注：{escape(record['notes'][:4000])}", body_style)
            )
        if index < len(slides) - 1:
            story.append(Spacer(1, 6 * mm))
    document.build(story)
    return stream.getvalue()


def export_content_bytes(export_format, source, fallback_title):
    adapters = {
        "pptx": export_pptx,
        "docx": export_docx,
        "pdf": export_pdf,
    }
    adapter = adapters.get(export_format)
    if not adapter:
        raise ContentExportError("unsupported content export format")
    return adapter(source or {}, fallback_title), MIME_TYPES[export_format]
