"""Office/PDF adapters for durable Education content versions.

The editable JSON remains authoritative. These adapters create portable files
on demand without placing generated bytes in a sandbox or treating an Office
file as the source of truth.
"""

from io import BytesIO
from html import escape
import re

from .presentation_themes import presentation_theme


class ContentExportError(RuntimeError):
    pass


MIME_TYPES = {
    "pptx": (
        "application/vnd.openxmlformats-officedocument.presentationml.presentation"
    ),
    "docx": (
        "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
    ),
    "pdf": "application/pdf",
}


def _plain_text(value):
    if value is None:
        return ""
    if isinstance(value, str):
        return re.sub(r"\s+", " ", re.sub(r"<[^>]+>", " ", value)).strip()
    if isinstance(value, (int, float, bool)):
        return str(value)
    if isinstance(value, list):
        return "\n".join(filter(None, (_plain_text(item) for item in value)))
    if isinstance(value, dict):
        preferred = (
            "content",
            "text",
            "description",
            "label",
            "name",
            "title",
            "prompt",
        )
        selected = [
            _plain_text(value[key])
            for key in preferred
            if key in value and _plain_text(value[key])
        ]
        if selected:
            return "\n".join(selected)
        return "\n".join(
            f"{str(key).replace('_', ' ')}：{_plain_text(item)}"
            for key, item in value.items()
            if _plain_text(item)
        )
    return str(value)


def _content_title(source, fallback):
    if isinstance(source, dict):
        for key in ("title", "lesson_title", "name"):
            value = _plain_text(source.get(key))
            if value:
                return value[:200]
    return str(fallback or "WeAgent Education 课件")[:200]


def _slide_records(source, fallback_title):
    title = _content_title(source, fallback_title)
    if isinstance(source, dict) and isinstance(source.get("slides"), list):
        slides = []
        for index, item in enumerate(source["slides"][:100], 1):
            if not isinstance(item, dict):
                slides.append(
                    {"title": f"第 {index} 页", "lines": [_plain_text(item)]}
                )
                continue
            slide_title = _plain_text(item.get("title")) or f"第 {index} 页"
            blocks = item.get("blocks")
            if not isinstance(blocks, list):
                blocks = [
                    value
                    for key, value in item.items()
                    if key not in {"id", "title", "layout", "speaker_notes"}
                ]
            lines = []
            for block in blocks[:40]:
                text = _plain_text(block)
                if text:
                    lines.extend(part for part in text.splitlines() if part.strip())
            slides.append(
                {
                    "title": slide_title[:200],
                    "lines": lines[:40] or ["（本页暂无正文）"],
                    "notes": _plain_text(item.get("speaker_notes")),
                    "layout": str(item.get("layout") or "content")[:80],
                }
            )
        return title, slides

    slides = []
    if isinstance(source, dict):
        objectives = source.get("objectives")
        if isinstance(objectives, list) and objectives:
            slides.append(
                {
                    "title": "教学目标",
                    "lines": [_plain_text(item) for item in objectives if _plain_text(item)],
                }
            )
        stages = source.get("stages")
        if isinstance(stages, list):
            for index, stage in enumerate(stages[:30], 1):
                stage_title = (
                    _plain_text(stage.get("name"))
                    if isinstance(stage, dict)
                    else ""
                ) or f"教学活动 {index}"
                lines = []
                if isinstance(stage, dict):
                    for key, label in (
                        ("duration_minutes", "时间"),
                        ("description", "活动"),
                        ("teacher_activity", "教师活动"),
                        ("student_activity", "学生活动"),
                        ("assessment", "评价"),
                    ):
                        value = _plain_text(stage.get(key))
                        if value:
                            suffix = " 分钟" if key == "duration_minutes" else ""
                            lines.append(f"{label}：{value}{suffix}")
                else:
                    lines.append(_plain_text(stage))
                slides.append({"title": stage_title[:200], "lines": lines})
        consumed = {"title", "lesson_title", "name", "objectives", "stages"}
        for key, value in list(source.items())[:50]:
            if key in consumed or key.endswith("_code"):
                continue
            text = _plain_text(value)
            if text:
                slides.append(
                    {
                        "title": str(key).replace("_", " ").title()[:200],
                        "lines": text.splitlines()[:40],
                    }
                )
    if not slides:
        slides = [{"title": "内容", "lines": [_plain_text(source) or "（暂无正文）"]}]
    return title, slides[:100]


def export_pptx(source, fallback_title):
    """Export a native, editable 16:9 deck from canonical SlideDocument JSON."""
    try:
        from pptx import Presentation
        from pptx.dml.color import RGBColor
        from pptx.enum.shapes import MSO_SHAPE
        from pptx.enum.text import MSO_ANCHOR, PP_ALIGN
        from pptx.oxml.ns import qn
        from pptx.oxml.xmlchemy import OxmlElement
        from pptx.util import Inches, Pt
    except ImportError as exc:
        raise ContentExportError("python-pptx adapter is unavailable") from exc

    title, slides = _slide_records(source, fallback_title)
    style, theme = presentation_theme(source if isinstance(source, dict) else {})

    def rgb(value):
        return RGBColor.from_string(str(value or "#000000").lstrip("#").upper())

    def set_run_font(run, size, color, bold=False):
        run.font.name = theme["font"]
        run.font.size = Pt(size)
        run.font.bold = bold
        run.font.color.rgb = rgb(color)
        properties = run._r.get_or_add_rPr()
        east_asian = properties.find(qn("a:ea"))
        if east_asian is None:
            east_asian = OxmlElement("a:ea")
            properties.append(east_asian)
        east_asian.set("typeface", theme["font"])

    def add_shape(slide, shape_type, left, top, width, height, color):
        shape = slide.shapes.add_shape(
            shape_type,
            Inches(left),
            Inches(top),
            Inches(width),
            Inches(height),
        )
        shape.fill.solid()
        shape.fill.fore_color.rgb = rgb(color)
        shape.line.fill.background()
        return shape

    def add_text(
        slide,
        text,
        left,
        top,
        width,
        height,
        *,
        size,
        color,
        bold=False,
        align=PP_ALIGN.LEFT,
        valign=MSO_ANCHOR.TOP,
    ):
        box = slide.shapes.add_textbox(
            Inches(left), Inches(top), Inches(width), Inches(height)
        )
        frame = box.text_frame
        frame.clear()
        frame.word_wrap = True
        frame.margin_left = Inches(0.02)
        frame.margin_right = Inches(0.02)
        frame.margin_top = Inches(0.02)
        frame.margin_bottom = Inches(0.02)
        frame.vertical_anchor = valign
        paragraph = frame.paragraphs[0]
        paragraph.alignment = align
        run = paragraph.add_run()
        run.text = str(text)
        set_run_font(run, size, color, bold)
        return box

    def decorate(slide, *, cover=False):
        if style == "clear_classroom":
            add_shape(
                slide, MSO_SHAPE.RECTANGLE, 0, 0, 13.333, 0.13, theme["primary"]
            )
            add_shape(
                slide,
                MSO_SHAPE.OVAL,
                12.25,
                5.85 if cover else 0.5,
                0.34,
                0.34,
                theme["accent"],
            )
        elif style == "paper_annotation":
            add_shape(
                slide, MSO_SHAPE.RECTANGLE, 0.62, 0, 0.035, 7.5, theme["accent"]
            )
            add_shape(
                slide, MSO_SHAPE.RECTANGLE, 0.4, 0.3, 1.25, 0.17, "#DCCFB8"
            )
        elif style == "storybook":
            add_shape(
                slide,
                MSO_SHAPE.OVAL,
                11.7,
                0,
                1.6,
                1.6,
                theme["accent"],
            )
            add_shape(
                slide,
                MSO_SHAPE.OVAL,
                0,
                6.35,
                1.15,
                1.15,
                theme["secondary"],
            )
        else:
            add_shape(
                slide, MSO_SHAPE.RECTANGLE, 0.58, 0.55, 0.08, 6.35, theme["primary"]
            )
            add_shape(
                slide, MSO_SHAPE.RECTANGLE, 11.65, 0, 1.68, 0.09, theme["accent"]
            )

    def add_body(slide, lines, record_layout):
        lines = [str(line).strip() for line in lines if str(line).strip()]
        lines = lines or ["（本页暂无正文）"]
        use_columns = record_layout == "two_column" or len(lines) > 6
        columns = [lines]
        if use_columns:
            split = (len(lines) + 1) // 2
            columns = [lines[:split], lines[split:]]
        lefts = [0.94] if len(columns) == 1 else [0.94, 6.82]
        widths = [11.45] if len(columns) == 1 else [5.48, 5.48]
        font_size = 27 if len(lines) <= 2 else (20 if len(lines) <= 8 else 17)
        for column_index, column in enumerate(columns):
            if style in {"storybook", "dark_focus"}:
                add_shape(
                    slide,
                    MSO_SHAPE.ROUNDED_RECTANGLE,
                    lefts[column_index] - 0.12,
                    1.76,
                    widths[column_index] + 0.24,
                    4.83,
                    theme["surface"],
                )
            box = slide.shapes.add_textbox(
                Inches(lefts[column_index]),
                Inches(1.94),
                Inches(widths[column_index]),
                Inches(4.42),
            )
            frame = box.text_frame
            frame.clear()
            frame.word_wrap = True
            frame.margin_left = Inches(0.1)
            frame.margin_right = Inches(0.1)
            frame.margin_top = Inches(0.08)
            frame.margin_bottom = Inches(0.08)
            frame.vertical_anchor = (
                MSO_ANCHOR.MIDDLE if len(lines) <= 2 else MSO_ANCHOR.TOP
            )
            for line_index, line in enumerate(column):
                paragraph = (
                    frame.paragraphs[0]
                    if line_index == 0
                    else frame.add_paragraph()
                )
                paragraph.text = line[:1200]
                paragraph.level = 0
                paragraph.space_after = Pt(11 if font_size >= 20 else 7)
                paragraph.line_spacing = 1.12
                if len(lines) > 2:
                    paragraph.text = f"•  {paragraph.text}"
                for run in paragraph.runs:
                    set_run_font(run, font_size, theme["text"])

    presentation = Presentation()
    presentation.slide_width = Inches(13.333)
    presentation.slide_height = Inches(7.5)
    presentation.core_properties.title = title
    presentation.core_properties.subject = style
    presentation.core_properties.keywords = (
        f"WeAgent Education, editable PPTX, {theme['label']}"
    )
    blank_layout = presentation.slide_layouts[6]

    cover = presentation.slides.add_slide(blank_layout)
    cover.background.fill.solid()
    cover.background.fill.fore_color.rgb = rgb(theme["background"])
    decorate(cover, cover=True)
    if style in {"clear_classroom", "paper_annotation"}:
        add_shape(
            cover, MSO_SHAPE.RECTANGLE, 0.86, 1.03, 0.12, 4.75, theme["accent"]
        )
    add_text(
        cover,
        theme["label"].upper(),
        1.22,
        0.85,
        8.8,
        0.45,
        size=14,
        color=theme["primary"],
        bold=True,
    )
    add_text(
        cover,
        title,
        1.2,
        1.43,
        10.85,
        2.45,
        size=52,
        color=theme["text"],
        bold=True,
        valign=MSO_ANCHOR.MIDDLE,
    )
    add_text(
        cover,
        "WeAgent Education · 可编辑课件",
        1.23,
        4.62,
        8.7,
        0.62,
        size=19,
        color=theme["muted"],
    )
    add_text(
        cover,
        f"{len(slides):02d}  SLIDES",
        10.42,
        6.58,
        1.75,
        0.35,
        size=11,
        color=theme["muted"],
        bold=True,
        align=PP_ALIGN.RIGHT,
    )

    for index, record in enumerate(slides, 1):
        slide = presentation.slides.add_slide(blank_layout)
        slide.background.fill.solid()
        slide.background.fill.fore_color.rgb = rgb(theme["background"])
        decorate(slide)
        add_text(
            slide,
            record["title"],
            0.9,
            0.5,
            10.85,
            0.88,
            size=36,
            color=theme["primary"],
            bold=True,
            valign=MSO_ANCHOR.MIDDLE,
        )
        if style != "storybook":
            add_shape(
                slide, MSO_SHAPE.RECTANGLE, 0.92, 1.47, 1.12, 0.06, theme["accent"]
            )
        add_body(
            slide,
            record.get("lines") or ["（本页暂无正文）"],
            record.get("layout") or "content",
        )
        add_text(
            slide,
            f"{index:02d}",
            11.72,
            6.87,
            0.62,
            0.28,
            size=10,
            color=theme["muted"],
            bold=True,
            align=PP_ALIGN.RIGHT,
        )

    stream = BytesIO()
    presentation.save(stream)
    return stream.getvalue()


def export_docx(source, fallback_title):
    try:
        from docx import Document
        from docx.enum.text import WD_ALIGN_PARAGRAPH
        from docx.oxml.ns import qn
        from docx.shared import Pt, RGBColor
    except ImportError as exc:
        raise ContentExportError("python-docx adapter is unavailable") from exc

    title, slides = _slide_records(source, fallback_title)
    document = Document()
    normal = document.styles["Normal"]
    normal.font.name = "Microsoft YaHei"
    normal._element.rPr.rFonts.set(qn("w:eastAsia"), "Microsoft YaHei")
    normal.font.size = Pt(10.5)

    heading = document.add_heading(title, level=0)
    heading.alignment = WD_ALIGN_PARAGRAPH.CENTER
    for run in heading.runs:
        run.font.name = "Microsoft YaHei"
        run._element.rPr.rFonts.set(qn("w:eastAsia"), "Microsoft YaHei")
        run.font.color.rgb = RGBColor(31, 93, 84)
    meta = document.add_paragraph("WeAgent Education · 可编辑内容导出")
    meta.alignment = WD_ALIGN_PARAGRAPH.CENTER

    for record in slides:
        document.add_heading(record["title"], level=1)
        for line in record.get("lines") or ["（暂无正文）"]:
            document.add_paragraph(str(line)[:4000], style="List Bullet")
        if record.get("notes"):
            document.add_heading("讲者备注", level=2)
            document.add_paragraph(record["notes"][:8000])

    stream = BytesIO()
    document.save(stream)
    return stream.getvalue()


def export_pdf(source, fallback_title):
    try:
        from reportlab.lib.enums import TA_CENTER
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
        from reportlab.lib.units import mm
        from reportlab.pdfbase import pdfmetrics
        from reportlab.pdfbase.cidfonts import UnicodeCIDFont
        from reportlab.platypus import (
            PageBreak,
            Paragraph,
            SimpleDocTemplate,
            Spacer,
        )
    except ImportError as exc:
        raise ContentExportError("ReportLab adapter is unavailable") from exc

    title, slides = _slide_records(source, fallback_title)
    try:
        pdfmetrics.registerFont(UnicodeCIDFont("STSong-Light"))
    except Exception as exc:
        raise ContentExportError("CJK PDF font adapter is unavailable") from exc

    stream = BytesIO()
    document = SimpleDocTemplate(
        stream,
        pagesize=A4,
        rightMargin=18 * mm,
        leftMargin=18 * mm,
        topMargin=18 * mm,
        bottomMargin=18 * mm,
        title=title,
    )
    sample = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "EducationTitle",
        parent=sample["Title"],
        fontName="STSong-Light",
        fontSize=22,
        leading=31,
        textColor="#1f5d54",
        alignment=TA_CENTER,
        spaceAfter=16,
    )
    subtitle_style = ParagraphStyle(
        "EducationSubtitle",
        parent=sample["BodyText"],
        fontName="STSong-Light",
        fontSize=10,
        leading=16,
        textColor="#71827e",
        alignment=TA_CENTER,
    )
    heading_style = ParagraphStyle(
        "EducationHeading",
        parent=sample["Heading1"],
        fontName="STSong-Light",
        fontSize=16,
        leading=23,
        textColor="#245f56",
        spaceAfter=10,
    )
    body_style = ParagraphStyle(
        "EducationBody",
        parent=sample["BodyText"],
        fontName="STSong-Light",
        fontSize=10.5,
        leading=18,
        textColor="#344641",
        leftIndent=5 * mm,
        firstLineIndent=-3 * mm,
        spaceAfter=6,
    )
    story = [
        Spacer(1, 42 * mm),
        Paragraph(escape(title), title_style),
        Paragraph("WeAgent Education · PDF 导出", subtitle_style),
        PageBreak(),
    ]
    for index, record in enumerate(slides):
        story.append(Paragraph(escape(record["title"]), heading_style))
        for line in record.get("lines") or ["（暂无正文）"]:
            story.append(Paragraph(f"• {escape(str(line)[:4000])}", body_style))
        if record.get("notes"):
            story.append(Spacer(1, 3 * mm))
            story.append(
                Paragraph(f"讲者备注：{escape(record['notes'][:4000])}", body_style)
            )
        if index < len(slides) - 1:
            story.append(Spacer(1, 6 * mm))
    document.build(story)
    return stream.getvalue()


def export_content_bytes(export_format, source, fallback_title):
    adapters = {
        "pptx": export_pptx,
        "docx": export_docx,
        "pdf": export_pdf,
    }
    adapter = adapters.get(export_format)
    if not adapter:
        raise ContentExportError("unsupported content export format")
    return adapter(source or {}, fallback_title), MIME_TYPES[export_format]
