<template>
  <div class="office-page"><AppSidebar/><main class="main">
    <header class="head"><div><h2>会议日程</h2><p>会议邀请、腾讯会议入口、个人日程与会议纪要</p></div><div><el-tag type="primary">本周 {{ meetings.length }} 场会议</el-tag><el-tag type="warning">待确认 {{ pending }} 项</el-tag><el-button type="primary" size="small" @click="openCreate">新建会议</el-button></div></header>
    <div class="grid"><section><div class="section-head"><b>近期会议</b><span>按时间排序 · 点击主题查看详情</span></div><el-card v-for="item in meetings" :key="item.id" class="meeting"><div class="time"><b>{{ date(item.start_time) }}</b><small>{{ time(item.start_time) }} - {{ time(item.end_time) }}</small></div><div class="body"><button @click="openDetail(item)">{{ item.title }}</button><p><el-tag size="mini" type="success">{{ item.status === 'scheduled' ? '待召开' : item.status }}</el-tag> {{ item.location || '未设置地点' }} · {{ (item.participants || []).length }} 位参会人</p><a v-if="item.meeting_link" :href="item.meeting_link" target="_blank" class="link">进入腾讯会议</a></div><div class="remind"><i class="el-icon-bell"></i><small>提前 30 / 15 分钟提醒</small></div></el-card><el-empty v-if="!meetings.length" description="暂无会议，点击右上角新建"/></section>
      <aside><div class="section-head"><b>我的时间线</b><span>会议与任务</span></div><div v-for="item in schedules" :key="item.id" class="timeline"><i :class="item.event_type === 'meeting' ? 'blue' : 'green'"></i><div><b>{{ time(item.start_time) }} {{ item.title }}</b><p>{{ item.event_type === 'meeting' ? '会议安排' : '行动项截止' }} · {{ date(item.start_time) }}</p></div></div><el-empty v-if="!schedules.length" :image-size="60" description="暂无日程"/></aside></div>
  </main>
  <el-dialog title="新建会议" :visible.sync="visible" width="560px"><el-form :model="form" label-width="88px" size="small"><el-form-item label="会议主题"><el-input v-model="form.title"/></el-form-item><el-form-item label="会议时间"><el-date-picker v-model="form.range" type="datetimerange" value-format="yyyy-MM-ddTHH:mm:ss" start-placeholder="开始" end-placeholder="结束" style="width:100%"/></el-form-item><el-form-item label="参会成员"><el-select v-model="form.participantIds" multiple style="width:100%" placeholder="可多选参会成员"><el-option v-for="m in members" :key="m.user_id" :label="m.display_name + ' · ' + role(m.role)" :value="m.user_id"/></el-select></el-form-item><el-form-item label="腾讯会议"><el-input v-model="form.meeting_link" placeholder="粘贴腾讯会议链接或会议号"/></el-form-item><el-form-item label="会议地点"><el-input v-model="form.location" placeholder="线上会议室 / A302"/></el-form-item></el-form><span slot="footer"><el-button @click="visible=false">取消</el-button><el-button type="primary" @click="create">创建并通知</el-button></span></el-dialog>
  <el-dialog :title="detail && detail.title" :visible.sync="detailVisible" width="680px"><div v-if="detail"><el-descriptions :column="2" border size="small"><el-descriptions-item label="时间">{{ detail.start_time }} 至 {{ detail.end_time }}</el-descriptions-item><el-descriptions-item label="地点">{{ detail.location || '-' }}</el-descriptions-item><el-descriptions-item label="腾讯会议"><a v-if="detail.meeting_link" :href="detail.meeting_link" target="_blank">进入会议</a><span v-else>-</span></el-descriptions-item><el-descriptions-item label="参会成员">{{ (detail.participants || []).map(x => x.display_name).join('、') || '-' }}</el-descriptions-item></el-descriptions><el-divider>会议纪要</el-divider><pre>{{ detail.minutes || '暂无纪要，可在会议结束后通过 AI 或人工整理。' }}</pre></div></el-dialog>
  </div>
</template>
<script>
import AppSidebar from '../components/Sidebar/index.vue'
export default { components:{AppSidebar}, data:()=>({visible:false,detailVisible:false,detail:null,form:{range:[],participantIds:[]}}), computed:{ws(){return this.$store.getters['workspace/activeWorkspace']||{}},meetings(){return this.$store.state.office.meetings},schedules(){return this.$store.state.office.schedules.slice(0,12)},members(){return (this.$store.state.office.organization||{members:[]}).members},pending(){return this.$store.state.office.notifications.filter(x=>!x.is_read).length}},watch:{'ws.id':{immediate:true,handler(){this.load()}}},methods:{async load(){if(!this.ws.id||this.ws.domain!=='office')return;await Promise.all([this.$store.dispatch('office/loadMeetings',this.ws.id),this.$store.dispatch('office/loadSchedules',this.ws.id),this.$store.dispatch('office/loadOrganization',this.ws.id),this.$store.dispatch('office/loadNotifications',this.ws.id)])},openCreate(){this.form={range:[],participantIds:[]};this.visible=true},async create(){if(!this.form.title||this.form.range.length!==2)return this.$message.warning('请完整填写会议主题和时间');const participants=this.members.filter(m=>this.form.participantIds.includes(m.user_id)).map(m=>({user_id:m.user_id,display_name:m.display_name}));await this.$store.dispatch('office/createMeeting',{workspace_id:this.ws.id,title:this.form.title,start_time:this.form.range[0],end_time:this.form.range[1],participants,meeting_link:this.form.meeting_link,location:this.form.location});this.visible=false;this.load();this.$message.success('会议已创建，参会成员已收到通知')},async openDetail(item){this.detail=await this.$store.dispatch('office/getMeeting',item.id);this.detailVisible=true},date(v){return(v||'').slice(5,10)},time(v){return(v||'').slice(11,16)},role(v){return({member:'组员',team_lead:'组长',department_head:'负责人'})[v]||v}}}
</script>
<style scoped>
.office-page{display:flex;min-height:100vh;padding:12px;gap:12px;background:#f3f6fb}.main{flex:1;padding:20px;background:#fff;border-radius:12px}.head,.section-head{display:flex;justify-content:space-between;align-items:center}.head{padding-bottom:14px;border-bottom:1px solid #edf0f5}.head h2{margin:0 0 5px}.head p,.section-head span,.timeline p{margin:0;color:#8592a6;font-size:13px}.head .el-tag,.head .el-button{margin-left:8px}.grid{display:grid;grid-template-columns:2fr 1fr;gap:16px;margin-top:16px}.section-head{padding:10px 0}.meeting{margin-bottom:8px}.meeting :deep(.el-card__body){display:flex;align-items:center;padding:12px}.time{width:115px;border-right:1px solid #edf1f6}.time b,.time small{display:block}.time small{color:#8491a4;margin-top:4px}.body{flex:1;padding:0 14px}.body button{border:0;background:none;padding:0;font:inherit;font-weight:bold;color:#2b6fbe;cursor:pointer}.body p{margin:6px 0;color:#738096;font-size:13px}.link{font-size:12px;color:#0a9a71}.remind{width:120px;color:#8c98a8;font-size:12px}.timeline{display:flex;gap:9px;padding:11px 6px;border-bottom:1px dashed #e6ecf4}.timeline i{width:9px;height:9px;border-radius:50%;margin-top:5px}.blue{background:#4f92ef}.green{background:#47b981}pre{white-space:pre-wrap;line-height:1.7;background:#f7f9fc;padding:12px}@media(max-width:900px){.grid{grid-template-columns:1fr}.remind{display:none}}
</style>
